# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporalio/api/stream/v1/message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'temporalio/api/stream/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporalio.api.common.v1 import message_pb2 as temporalio_dot_api_dot_common_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&temporalio/api/stream/v1/message.proto\x12)temporal.server.chasm.lib.stream.proto.v1\x1a$temporal/api/common/v1/message.proto\"\xdd\x02\n\rStreamMessage\x12-\n\x04\x62ody\x18\x01 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload\x12X\n\x08metadata\x18\x02 \x03(\x0b\x32\x46.temporal.server.chasm.lib.stream.proto.v1.StreamMessage.MetadataEntry\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x16\n\x0etopic_sequence\x18\x04 \x01(\x03\x12J\n\x04kind\x18\x05 \x01(\x0e\x32<.temporal.server.chasm.lib.stream.proto.v1.StreamMessageKind\x1aP\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload:\x02\x38\x01\"`\n\x12StreamMessageBatch\x12J\n\x08messages\x18\x01 \x03(\x0b\x32\x38.temporal.server.chasm.lib.stream.proto.v1.StreamMessage*u\n\x11StreamMessageKind\x12#\n\x1fSTREAM_MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x1c\n\x18STREAM_MESSAGE_KIND_DATA\x10\x01\x12\x1d\n\x19STREAM_MESSAGE_KIND_FLUSH\x10\x02\x42>Z<go.temporal.io/server/chasm/lib/stream/gen/streampb;streampbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temporalio.api.streamservice.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<go.temporal.io/server/chasm/lib/stream/gen/streampb;streampb'
  _globals['_STREAMMESSAGE_METADATAENTRY']._loaded_options = None
  _globals['_STREAMMESSAGE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STREAMMESSAGEKIND']._serialized_start=573
  _globals['_STREAMMESSAGEKIND']._serialized_end=690
  _globals['_STREAMMESSAGE']._serialized_start=124
  _globals['_STREAMMESSAGE']._serialized_end=473
  _globals['_STREAMMESSAGE_METADATAENTRY']._serialized_start=393
  _globals['_STREAMMESSAGE_METADATAENTRY']._serialized_end=473
  _globals['_STREAMMESSAGEBATCH']._serialized_start=475
  _globals['_STREAMMESSAGEBATCH']._serialized_end=571
# @@protoc_insertion_point(module_scope)
