"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message

import temporalio.api.common.v1.message_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StreamMessageKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StreamMessageKindEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _StreamMessageKind.ValueType
    ],
    builtins.type,
):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STREAM_MESSAGE_KIND_UNSPECIFIED: _StreamMessageKind.ValueType  # 0
    STREAM_MESSAGE_KIND_DATA: _StreamMessageKind.ValueType  # 1
    STREAM_MESSAGE_KIND_FLUSH: _StreamMessageKind.ValueType  # 2
    """Producer signalling a delivery boundary. Carries no body and consumes an
    offset like any other message. A consumer uses it to end a turn without
    waiting out an idle timeout.
    """

class StreamMessageKind(
    _StreamMessageKind, metaclass=_StreamMessageKindEnumTypeWrapper
): ...

STREAM_MESSAGE_KIND_UNSPECIFIED: StreamMessageKind.ValueType  # 0
STREAM_MESSAGE_KIND_DATA: StreamMessageKind.ValueType  # 1
STREAM_MESSAGE_KIND_FLUSH: StreamMessageKind.ValueType  # 2
"""Producer signalling a delivery boundary. Carries no body and consumes an
offset like any other message. A consumer uses it to end a turn without
waiting out an idle timeout.
"""
global___StreamMessageKind = StreamMessageKind

class StreamMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> temporal.api.common.v1.message_pb2.Payload: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: temporal.api.common.v1.message_pb2.Payload | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...

    BODY_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    TOPIC_FIELD_NUMBER: builtins.int
    TOPIC_SEQUENCE_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    @property
    def body(self) -> temporal.api.common.v1.message_pb2.Payload: ...
    @property
    def metadata(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, temporal.api.common.v1.message_pb2.Payload
    ]:
        """Producer-supplied provenance. The server does not populate this today."""
    topic: builtins.str
    topic_sequence: builtins.int
    """Position within this topic. The global offset orders the whole stream;
    this lets a consumer reason about one topic without decoding the rest.
    """
    kind: global___StreamMessageKind.ValueType
    offset: builtins.int
    """Position in the whole stream, set on read and never stored. A consumer
    that resumes at message granularity needs it, and a topic-filtered read
    leaves gaps that make it underivable from the response alone.
    """
    def __init__(
        self,
        *,
        body: temporal.api.common.v1.message_pb2.Payload | None = ...,
        metadata: collections.abc.Mapping[
            builtins.str, temporal.api.common.v1.message_pb2.Payload
        ]
        | None = ...,
        topic: builtins.str = ...,
        topic_sequence: builtins.int = ...,
        kind: global___StreamMessageKind.ValueType = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["body", b"body"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "body",
            b"body",
            "kind",
            b"kind",
            "metadata",
            b"metadata",
            "offset",
            b"offset",
            "topic",
            b"topic",
            "topic_sequence",
            b"topic_sequence",
        ],
    ) -> None: ...

global___StreamMessage = StreamMessage

class StreamMessageBatch(google.protobuf.message.Message):
    """One append is one batch, and one batch is one log node. The server stores
    this serialized and opaque; it decodes only to trim a partial first page or
    to apply a topic filter.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___StreamMessage
    ]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___StreamMessage] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["messages", b"messages"]
    ) -> None: ...

global___StreamMessageBatch = StreamMessageBatch
