# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporalio/api/stream/v1/message.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporalio.api.common.v1 import (
    message_pb2 as temporal_dot_api_dot_common_dot_v1_dot_message__pb2,
)
from temporalio.api.stream.v1 import (
    message_pb2 as temporal_dot_api_dot_stream_dot_v1_dot_message__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&temporalio/api/stream/v1/message.proto\x12)temporal.server.chasm.lib.stream.proto.v1\x1a$temporal/api/common/v1/message.proto\x1a$temporal/api/stream/v1/message.proto"\xf7\x02\n\x0cStreamRecord\x12-\n\x04\x62ody\x18\x01 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload\x12W\n\x08metadata\x18\x02 \x03(\x0b\x32\x45.temporal.server.chasm.lib.stream.proto.v1.StreamRecord.MetadataEntry\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\x03\x12\x36\n\x04kind\x18\x05 \x01(\x0e\x32(.temporal.api.stream.v1.StreamRecordKind\x12\x0e\n\x06offset\x18\x06 \x01(\x03\x12\x13\n\x0bproducer_id\x18\x07 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x08 \x01(\x03\x1aP\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload:\x02\x38\x01"]\n\x11StreamRecordBatch\x12H\n\x07records\x18\x01 \x03(\x0b\x32\x37.temporal.server.chasm.lib.stream.proto.v1.StreamRecordB>Z<go.temporal.io/server/chasm/lib/stream/gen/streampb;streampbb\x06proto3'
)


_STREAMRECORD = DESCRIPTOR.message_types_by_name["StreamRecord"]
_STREAMRECORD_METADATAENTRY = _STREAMRECORD.nested_types_by_name["MetadataEntry"]
_STREAMRECORDBATCH = DESCRIPTOR.message_types_by_name["StreamRecordBatch"]
StreamRecord = _reflection.GeneratedProtocolMessageType(
    "StreamRecord",
    (_message.Message,),
    {
        "MetadataEntry": _reflection.GeneratedProtocolMessageType(
            "MetadataEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _STREAMRECORD_METADATAENTRY,
                "__module__": "temporalio.api.streamservice.v1.message_pb2",
                # @@protoc_insertion_point(class_scope:temporal.server.chasm.lib.stream.proto.v1.StreamRecord.MetadataEntry)
            },
        ),
        "DESCRIPTOR": _STREAMRECORD,
        "__module__": "temporalio.api.streamservice.v1.message_pb2",
        # @@protoc_insertion_point(class_scope:temporal.server.chasm.lib.stream.proto.v1.StreamRecord)
    },
)
_sym_db.RegisterMessage(StreamRecord)
_sym_db.RegisterMessage(StreamRecord.MetadataEntry)

StreamRecordBatch = _reflection.GeneratedProtocolMessageType(
    "StreamRecordBatch",
    (_message.Message,),
    {
        "DESCRIPTOR": _STREAMRECORDBATCH,
        "__module__": "temporalio.api.streamservice.v1.message_pb2",
        # @@protoc_insertion_point(class_scope:temporal.server.chasm.lib.stream.proto.v1.StreamRecordBatch)
    },
)
_sym_db.RegisterMessage(StreamRecordBatch)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z<go.temporal.io/server/chasm/lib/stream/gen/streampb;streampb"
    )
    _STREAMRECORD_METADATAENTRY._options = None
    _STREAMRECORD_METADATAENTRY._serialized_options = b"8\001"
    _STREAMRECORD._serialized_start = 162
    _STREAMRECORD._serialized_end = 537
    _STREAMRECORD_METADATAENTRY._serialized_start = 457
    _STREAMRECORD_METADATAENTRY._serialized_end = 537
    _STREAMRECORDBATCH._serialized_start = 539
    _STREAMRECORDBATCH._serialized_end = 632
# @@protoc_insertion_point(module_scope)
