"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message

import temporalio.api.common.v1.message_pb2
import temporalio.api.stream.v1.message_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StreamRecord(google.protobuf.message.Message):
    """The stored shape of temporal.api.stream.v1.StreamRecord plus the offset a
    read assigns. Field for field the public record, so one crosses the frontend
    in either direction without translation.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> temporalio.api.common.v1.message_pb2.Payload: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: temporalio.api.common.v1.message_pb2.Payload | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...

    BODY_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    TOPIC_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    PRODUCER_ID_FIELD_NUMBER: builtins.int
    ATTEMPT_FIELD_NUMBER: builtins.int
    @property
    def body(self) -> temporalio.api.common.v1.message_pb2.Payload: ...
    @property
    def metadata(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, temporalio.api.common.v1.message_pb2.Payload
    ]:
        """Producer-supplied provenance, stored as sent."""
    topic: builtins.str
    sequence: builtins.int
    """The producer's position within its attempt, or -1 when unnumbered. Stored
    as sent; the global offset is what orders the stream.
    """
    kind: temporalio.api.stream.v1.message_pb2.StreamRecordKind.ValueType
    """Settled to DATA on append when left unspecified, so a retry hashes the
    same bytes and a reader never sees the zero value.
    """
    offset: builtins.int
    """Position in the whole stream, set on read and never stored. A consumer
    that resumes at record granularity needs it, and a topic-filtered read
    leaves gaps that make it underivable from the response alone.
    """
    producer_id: builtins.str
    """Who wrote the record. Empty when the owning Workflow did: its publish
    command clears the field, whatever the worker sent.
    """
    attempt: builtins.int
    """The producer's attempt, stored as sent. Readers treat a later attempt by
    the same producer as superseding what the earlier one wrote.
    """
    def __init__(
        self,
        *,
        body: temporalio.api.common.v1.message_pb2.Payload | None = ...,
        metadata: collections.abc.Mapping[
            builtins.str, temporalio.api.common.v1.message_pb2.Payload
        ]
        | None = ...,
        topic: builtins.str = ...,
        sequence: builtins.int = ...,
        kind: temporalio.api.stream.v1.message_pb2.StreamRecordKind.ValueType = ...,
        offset: builtins.int = ...,
        producer_id: builtins.str = ...,
        attempt: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["body", b"body"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "attempt",
            b"attempt",
            "body",
            b"body",
            "kind",
            b"kind",
            "metadata",
            b"metadata",
            "offset",
            b"offset",
            "producer_id",
            b"producer_id",
            "sequence",
            b"sequence",
            "topic",
            b"topic",
        ],
    ) -> None: ...

global___StreamRecord = StreamRecord

class StreamRecordBatch(google.protobuf.message.Message):
    """One append is one batch, and one batch is one data node. The server stores
    this serialized and opaque; it decodes only to trim a partial first page or
    to apply a topic filter.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDS_FIELD_NUMBER: builtins.int
    @property
    def records(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___StreamRecord
    ]: ...
    def __init__(
        self,
        *,
        records: collections.abc.Iterable[global___StreamRecord] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["records", b"records"]
    ) -> None: ...

global___StreamRecordBatch = StreamRecordBatch
