"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message

import temporalio.api.common.v1.message_pb2
import temporalio.api.streamservice.v1.message_pb2
import temporalio.api.streamservice.v1.stream_state_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class CreateStreamInput(google.protobuf.message.Message):
    """The frontend-facing shapes are defined here rather than in the public API
    because streams have no public API yet. Keeping them in a nested
    frontend_request mirrors the other CHASM libraries, so promoting them later
    is a package move rather than a redesign.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    LIFECYCLE_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    @property
    def lifecycle(
        self,
    ) -> temporalio.api.streamservice.v1.stream_state_pb2.StreamLifecycle: ...
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        lifecycle: temporalio.api.streamservice.v1.stream_state_pb2.StreamLifecycle
        | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["lifecycle", b"lifecycle"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "lifecycle",
            b"lifecycle",
            "namespace",
            b"namespace",
            "stream_id",
            b"stream_id",
        ],
    ) -> None: ...

global___CreateStreamInput = CreateStreamInput

class CreateStreamOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    run_id: builtins.str
    def __init__(
        self,
        *,
        run_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["run_id", b"run_id"]
    ) -> None: ...

global___CreateStreamOutput = CreateStreamOutput

class AddMessagesInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    PRODUCER_ID_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    EXPECTED_OFFSET_FIELD_NUMBER: builtins.int
    USE_EXPECTED_OFFSET_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    run_id: builtins.str
    """Optional. Supplying it skips resolving the stream's current run, which is
    a persistence lookup on every call. CreateStream returns it.
    """
    @property
    def records(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        temporalio.api.streamservice.v1.message_pb2.StreamRecord
    ]: ...
    producer_id: builtins.str
    """Idempotency, all optional. Supply a producer identity and sequence, or an
    expected offset, or neither and accept at-least-once.
    """
    sequence: builtins.int
    expected_offset: builtins.int
    """Guarded by use_expected_offset because proto3 optional is not supported
    by this repo's helper generator.
    """
    use_expected_offset: builtins.bool
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        run_id: builtins.str = ...,
        records: collections.abc.Iterable[
            temporalio.api.streamservice.v1.message_pb2.StreamRecord
        ]
        | None = ...,
        producer_id: builtins.str = ...,
        sequence: builtins.int = ...,
        expected_offset: builtins.int = ...,
        use_expected_offset: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "expected_offset",
            b"expected_offset",
            "namespace",
            b"namespace",
            "producer_id",
            b"producer_id",
            "records",
            b"records",
            "run_id",
            b"run_id",
            "sequence",
            b"sequence",
            "stream_id",
            b"stream_id",
            "use_expected_offset",
            b"use_expected_offset",
        ],
    ) -> None: ...

global___AddMessagesInput = AddMessagesInput

class AddMessagesOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRST_OFFSET_FIELD_NUMBER: builtins.int
    NEXT_OFFSET_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    DEDUPLICATED_FIELD_NUMBER: builtins.int
    first_offset: builtins.int
    next_offset: builtins.int
    count: builtins.int
    deduplicated: builtins.bool
    """True when a retry matched a recorded sequence and nothing was appended."""
    def __init__(
        self,
        *,
        first_offset: builtins.int = ...,
        next_offset: builtins.int = ...,
        count: builtins.int = ...,
        deduplicated: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "count",
            b"count",
            "deduplicated",
            b"deduplicated",
            "first_offset",
            b"first_offset",
            "next_offset",
            b"next_offset",
        ],
    ) -> None: ...

global___AddMessagesOutput = AddMessagesOutput

class FinishWritingInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    PRODUCER_ID_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    producer_id: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        producer_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "producer_id",
            b"producer_id",
            "stream_id",
            b"stream_id",
        ],
    ) -> None: ...

global___FinishWritingInput = FinishWritingInput

class FinishWritingOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___FinishWritingOutput = FinishWritingOutput

class SubscribeWorkflowInput(google.protobuf.message.Message):
    """Registers a Workflow as a consumer of a stream it owns. The cursor lands in
    the Workflow's own state, so from then on each of its Workflow Tasks carries
    the next range and records what it consumed.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    OWNER_RUN_ID_FIELD_NUMBER: builtins.int
    STREAM_NAME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    START_OFFSET_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    owner_run_id: builtins.str
    """Optional. Pins to one run, so a caller that has continued as new is not
    silently redirected to the successor's stream, which starts empty and at
    offset zero. Empty means whichever run is current.
    """
    stream_name: builtins.str
    """Name of the stream within the Workflow, for a stream it owns."""
    stream_id: builtins.str
    """Id of a standalone stream in another execution. Exactly one of this and
    stream_name is set.
    """
    start_offset: builtins.int
    """Where to start. Resolved here rather than at delivery, so the first
    recorded range starts from a fact instead of a reading.
    """
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        workflow_id: builtins.str = ...,
        owner_run_id: builtins.str = ...,
        stream_name: builtins.str = ...,
        stream_id: builtins.str = ...,
        start_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "owner_run_id",
            b"owner_run_id",
            "start_offset",
            b"start_offset",
            "stream_id",
            b"stream_id",
            "stream_name",
            b"stream_name",
            "workflow_id",
            b"workflow_id",
        ],
    ) -> None: ...

global___SubscribeWorkflowInput = SubscribeWorkflowInput

class SubscribeWorkflowOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_OFFSET_FIELD_NUMBER: builtins.int
    start_offset: builtins.int
    def __init__(
        self,
        *,
        start_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["start_offset", b"start_offset"]
    ) -> None: ...

global___SubscribeWorkflowOutput = SubscribeWorkflowOutput

class PollMessagesInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    FROM_OFFSET_FIELD_NUMBER: builtins.int
    MAX_MESSAGES_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int
    WAIT_NEW_MESSAGES_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    run_id: builtins.str
    """Optional, as on AddMessagesInput."""
    from_offset: builtins.int
    max_messages: builtins.int
    @property
    def topics(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Filters by exact topic. Offsets are assigned over the unfiltered stream, so
        next_offset advances past filtered-out records too.
        """
    wait_new_messages: builtins.bool
    """When set and the reader is caught up, block until something arrives, the
    stream closes, or the server's long-poll timeout elapses. A timeout returns
    an empty response rather than an error, so the caller simply polls again.
    """
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        run_id: builtins.str = ...,
        from_offset: builtins.int = ...,
        max_messages: builtins.int = ...,
        topics: collections.abc.Iterable[builtins.str] | None = ...,
        wait_new_messages: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "from_offset",
            b"from_offset",
            "max_messages",
            b"max_messages",
            "namespace",
            b"namespace",
            "run_id",
            b"run_id",
            "stream_id",
            b"stream_id",
            "topics",
            b"topics",
            "wait_new_messages",
            b"wait_new_messages",
        ],
    ) -> None: ...

global___PollMessagesInput = PollMessagesInput

class PollMessagesOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDS_FIELD_NUMBER: builtins.int
    NEXT_OFFSET_FIELD_NUMBER: builtins.int
    HEAD_OFFSET_FIELD_NUMBER: builtins.int
    CLOSED_FIELD_NUMBER: builtins.int
    CLOSE_REASON_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    @property
    def records(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        temporalio.api.streamservice.v1.message_pb2.StreamRecord
    ]: ...
    next_offset: builtins.int
    head_offset: builtins.int
    closed: builtins.bool
    @property
    def close_reason(self) -> temporal.api.common.v1.message_pb2.Payload: ...
    run_id: builtins.str
    """The execution holding the stream. A workflow task slice built from this
    read names the run it came from.
    """
    def __init__(
        self,
        *,
        records: collections.abc.Iterable[
            temporalio.api.streamservice.v1.message_pb2.StreamRecord
        ]
        | None = ...,
        next_offset: builtins.int = ...,
        head_offset: builtins.int = ...,
        closed: builtins.bool = ...,
        close_reason: temporal.api.common.v1.message_pb2.Payload | None = ...,
        run_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["close_reason", b"close_reason"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "close_reason",
            b"close_reason",
            "closed",
            b"closed",
            "head_offset",
            b"head_offset",
            "next_offset",
            b"next_offset",
            "records",
            b"records",
            "run_id",
            b"run_id",
        ],
    ) -> None: ...

global___PollMessagesOutput = PollMessagesOutput

class DescribeStreamInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace", b"namespace", "stream_id", b"stream_id"
        ],
    ) -> None: ...

global___DescribeStreamInput = DescribeStreamInput

class PollWorkflowMessagesInput(google.protobuf.message.Message):
    """A stream a workflow owns lives inside that workflow's execution, so it has
    no standalone id to address it by. It is named by its owner and its name
    instead, and routed on the owner.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    OWNER_RUN_ID_FIELD_NUMBER: builtins.int
    STREAM_NAME_FIELD_NUMBER: builtins.int
    FROM_OFFSET_FIELD_NUMBER: builtins.int
    MAX_MESSAGES_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int
    WAIT_NEW_MESSAGES_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    owner_run_id: builtins.str
    """Optional. Pins to one run, so a caller that has continued as new is not
    silently redirected to the successor's stream, which starts empty and at
    offset zero. Empty means whichever run is current.
    """
    stream_name: builtins.str
    """Empty means the workflow's default output stream."""
    from_offset: builtins.int
    max_messages: builtins.int
    @property
    def topics(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Filters as on PollMessagesInput."""
    wait_new_messages: builtins.bool
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        workflow_id: builtins.str = ...,
        owner_run_id: builtins.str = ...,
        stream_name: builtins.str = ...,
        from_offset: builtins.int = ...,
        max_messages: builtins.int = ...,
        topics: collections.abc.Iterable[builtins.str] | None = ...,
        wait_new_messages: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "from_offset",
            b"from_offset",
            "max_messages",
            b"max_messages",
            "namespace",
            b"namespace",
            "owner_run_id",
            b"owner_run_id",
            "stream_name",
            b"stream_name",
            "topics",
            b"topics",
            "wait_new_messages",
            b"wait_new_messages",
            "workflow_id",
            b"workflow_id",
        ],
    ) -> None: ...

global___PollWorkflowMessagesInput = PollWorkflowMessagesInput

class DescribeWorkflowStreamInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    OWNER_RUN_ID_FIELD_NUMBER: builtins.int
    STREAM_NAME_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    owner_run_id: builtins.str
    """Optional. Pins to one run, so a caller that has continued as new is not
    silently redirected to the successor's stream, which starts empty and at
    offset zero. Empty means whichever run is current.
    """
    stream_name: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        workflow_id: builtins.str = ...,
        owner_run_id: builtins.str = ...,
        stream_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "owner_run_id",
            b"owner_run_id",
            "stream_name",
            b"stream_name",
            "workflow_id",
            b"workflow_id",
        ],
    ) -> None: ...

global___DescribeWorkflowStreamInput = DescribeWorkflowStreamInput

class AddWorkflowMessagesInput(google.protobuf.message.Message):
    """Appending to a stream a workflow owns, from outside that workflow. The
    workflow's own publishes ride its Workflow Task instead.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    OWNER_RUN_ID_FIELD_NUMBER: builtins.int
    STREAM_NAME_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    PRODUCER_ID_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    owner_run_id: builtins.str
    """Optional. Pins to one run, so a caller that has continued as new is not
    silently redirected to the successor's stream, which starts empty and at
    offset zero. Empty means whichever run is current.
    """
    stream_name: builtins.str
    """Empty means the workflow's default output stream."""
    @property
    def records(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        temporalio.api.streamservice.v1.message_pb2.StreamRecord
    ]: ...
    producer_id: builtins.str
    """Optional idempotency, as on AddMessagesInput."""
    sequence: builtins.int
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        workflow_id: builtins.str = ...,
        owner_run_id: builtins.str = ...,
        stream_name: builtins.str = ...,
        records: collections.abc.Iterable[
            temporalio.api.streamservice.v1.message_pb2.StreamRecord
        ]
        | None = ...,
        producer_id: builtins.str = ...,
        sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "owner_run_id",
            b"owner_run_id",
            "producer_id",
            b"producer_id",
            "records",
            b"records",
            "sequence",
            b"sequence",
            "stream_name",
            b"stream_name",
            "workflow_id",
            b"workflow_id",
        ],
    ) -> None: ...

global___AddWorkflowMessagesInput = AddWorkflowMessagesInput

class DescribeStreamOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    @property
    def state(self) -> temporalio.api.streamservice.v1.stream_state_pb2.StreamState: ...
    def __init__(
        self,
        *,
        state: temporalio.api.streamservice.v1.stream_state_pb2.StreamState
        | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["state", b"state"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["state", b"state"]
    ) -> None: ...

global___DescribeStreamOutput = DescribeStreamOutput

class CloseStreamInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    @property
    def reason(self) -> temporal.api.common.v1.message_pb2.Payload: ...
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        reason: temporal.api.common.v1.message_pb2.Payload | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["reason", b"reason"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace", b"namespace", "reason", b"reason", "stream_id", b"stream_id"
        ],
    ) -> None: ...

global___CloseStreamInput = CloseStreamInput

class CloseStreamOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseStreamOutput = CloseStreamOutput

class TruncateStreamInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    NEW_BASE_OFFSET_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    new_base_offset: builtins.int
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        new_base_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "new_base_offset",
            b"new_base_offset",
            "stream_id",
            b"stream_id",
        ],
    ) -> None: ...

global___TruncateStreamInput = TruncateStreamInput

class TruncateStreamOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___TruncateStreamOutput = TruncateStreamOutput

class DeleteStreamInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    FORCE_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    force: builtins.bool
    """Delete even while a workflow consumer is active. Without it the call is
    refused, because the consumer's History depends on ranges the deletion
    takes with it.
    """
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        force: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "force", b"force", "namespace", b"namespace", "stream_id", b"stream_id"
        ],
    ) -> None: ...

global___DeleteStreamInput = DeleteStreamInput

class DeleteStreamOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteStreamOutput = DeleteStreamOutput

class CreateStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___CreateStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___CreateStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___CreateStreamRequest = CreateStreamRequest

class CreateStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___CreateStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___CreateStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___CreateStreamResponse = CreateStreamResponse

class AddMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___AddMessagesInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___AddMessagesInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___AddMessagesRequest = AddMessagesRequest

class AddMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___AddMessagesOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___AddMessagesOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___AddMessagesResponse = AddMessagesResponse

class FinishWritingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___FinishWritingInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___FinishWritingInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___FinishWritingRequest = FinishWritingRequest

class FinishWritingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___FinishWritingOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___FinishWritingOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___FinishWritingResponse = FinishWritingResponse

class SubscribeWorkflowRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___SubscribeWorkflowInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___SubscribeWorkflowInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___SubscribeWorkflowRequest = SubscribeWorkflowRequest

class SubscribeWorkflowResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___SubscribeWorkflowOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___SubscribeWorkflowOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___SubscribeWorkflowResponse = SubscribeWorkflowResponse

class PollMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___PollMessagesInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___PollMessagesInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___PollMessagesRequest = PollMessagesRequest

class PollMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___PollMessagesOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___PollMessagesOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___PollMessagesResponse = PollMessagesResponse

class DescribeStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___DescribeStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___DescribeStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___DescribeStreamRequest = DescribeStreamRequest

class DescribeStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___DescribeStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___DescribeStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___DescribeStreamResponse = DescribeStreamResponse

class PollWorkflowMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___PollWorkflowMessagesInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___PollWorkflowMessagesInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___PollWorkflowMessagesRequest = PollWorkflowMessagesRequest

class PollWorkflowMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___PollMessagesOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___PollMessagesOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___PollWorkflowMessagesResponse = PollWorkflowMessagesResponse

class DescribeWorkflowStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___DescribeWorkflowStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___DescribeWorkflowStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___DescribeWorkflowStreamRequest = DescribeWorkflowStreamRequest

class DescribeWorkflowStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___DescribeStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___DescribeStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___DescribeWorkflowStreamResponse = DescribeWorkflowStreamResponse

class RegisterStreamConsumerInput(google.protobuf.message.Message):
    """Registering a consumer on a stream in another execution. Split out from
    SubscribeWorkflow because the two halves live on different shards: the pin
    goes on the stream, the cursor goes on the consuming workflow, and a handler
    can only reach the shard it was routed to.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    CONSUMER_WORKFLOW_ID_FIELD_NUMBER: builtins.int
    CONSUMER_RUN_ID_FIELD_NUMBER: builtins.int
    START_OFFSET_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    stream_id: builtins.str
    consumer_workflow_id: builtins.str
    """The workflow that will consume. Together with the run it names the pin,
    so a later run of the same workflow id registers fresh rather than
    inheriting a closed run's floor.
    """
    consumer_run_id: builtins.str
    start_offset: builtins.int
    """Negative means from wherever the stream is when the pin is taken. Resolved
    here, where the frontier is, and returned so the cursor records a fact.
    """
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        stream_id: builtins.str = ...,
        consumer_workflow_id: builtins.str = ...,
        consumer_run_id: builtins.str = ...,
        start_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "consumer_run_id",
            b"consumer_run_id",
            "consumer_workflow_id",
            b"consumer_workflow_id",
            "namespace",
            b"namespace",
            "start_offset",
            b"start_offset",
            "stream_id",
            b"stream_id",
        ],
    ) -> None: ...

global___RegisterStreamConsumerInput = RegisterStreamConsumerInput

class RegisterStreamConsumerOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_OFFSET_FIELD_NUMBER: builtins.int
    KNOWN_HEAD_FIELD_NUMBER: builtins.int
    start_offset: builtins.int
    known_head: builtins.int
    """The frontier at registration, so the cursor starts with a known head
    instead of waiting for the first push.
    """
    def __init__(
        self,
        *,
        start_offset: builtins.int = ...,
        known_head: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "known_head", b"known_head", "start_offset", b"start_offset"
        ],
    ) -> None: ...

global___RegisterStreamConsumerOutput = RegisterStreamConsumerOutput

class AdvanceConsumerHeadInput(google.protobuf.message.Message):
    """Telling one consumer that the frontier moved. Routed to the consumer, which
    is not where the stream lives.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    OWNER_RUN_ID_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    HEAD_OFFSET_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    owner_run_id: builtins.str
    """The run that subscribed. A successor from continue-as-new holds no cursor
    for this stream, so pushing the frontier at it would land nowhere.
    """
    stream_id: builtins.str
    head_offset: builtins.int
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        workflow_id: builtins.str = ...,
        owner_run_id: builtins.str = ...,
        stream_id: builtins.str = ...,
        head_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "head_offset",
            b"head_offset",
            "namespace",
            b"namespace",
            "owner_run_id",
            b"owner_run_id",
            "stream_id",
            b"stream_id",
            "workflow_id",
            b"workflow_id",
        ],
    ) -> None: ...

global___AdvanceConsumerHeadInput = AdvanceConsumerHeadInput

class AdvanceConsumerHeadOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONSUMER_CLOSED_FIELD_NUMBER: builtins.int
    SUCCESSOR_RUN_ID_FIELD_NUMBER: builtins.int
    SUCCESSOR_START_OFFSET_FIELD_NUMBER: builtins.int
    consumer_closed: builtins.bool
    """The run that held the pin is closed and no current run of the workflow
    consumes the stream, so the stream can release the pin.
    """
    successor_run_id: builtins.str
    """The run that held the pin is closed but a successor carries the
    subscription, so the stream re-keys the pin to it, with the floor the
    successor's cursor started from.
    """
    successor_start_offset: builtins.int
    def __init__(
        self,
        *,
        consumer_closed: builtins.bool = ...,
        successor_run_id: builtins.str = ...,
        successor_start_offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "consumer_closed",
            b"consumer_closed",
            "successor_run_id",
            b"successor_run_id",
            "successor_start_offset",
            b"successor_start_offset",
        ],
    ) -> None: ...

global___AdvanceConsumerHeadOutput = AdvanceConsumerHeadOutput

class AddWorkflowMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___AddWorkflowMessagesInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___AddWorkflowMessagesInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___AddWorkflowMessagesRequest = AddWorkflowMessagesRequest

class AddWorkflowMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___AddMessagesOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___AddMessagesOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___AddWorkflowMessagesResponse = AddWorkflowMessagesResponse

class RegisterStreamConsumerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___RegisterStreamConsumerInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___RegisterStreamConsumerInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___RegisterStreamConsumerRequest = RegisterStreamConsumerRequest

class RegisterStreamConsumerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___RegisterStreamConsumerOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___RegisterStreamConsumerOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___RegisterStreamConsumerResponse = RegisterStreamConsumerResponse

class AdvanceConsumerHeadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___AdvanceConsumerHeadInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___AdvanceConsumerHeadInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___AdvanceConsumerHeadRequest = AdvanceConsumerHeadRequest

class AdvanceConsumerHeadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___AdvanceConsumerHeadOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___AdvanceConsumerHeadOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___AdvanceConsumerHeadResponse = AdvanceConsumerHeadResponse

class CloseStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___CloseStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___CloseStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___CloseStreamRequest = CloseStreamRequest

class CloseStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___CloseStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___CloseStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___CloseStreamResponse = CloseStreamResponse

class TruncateStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___TruncateStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___TruncateStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___TruncateStreamRequest = TruncateStreamRequest

class TruncateStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___TruncateStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___TruncateStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___TruncateStreamResponse = TruncateStreamResponse

class ListStreamsInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    page_size: builtins.int
    next_page_token: builtins.bytes
    query: builtins.str
    def __init__(
        self,
        *,
        namespace: builtins.str = ...,
        page_size: builtins.int = ...,
        next_page_token: builtins.bytes = ...,
        query: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "namespace",
            b"namespace",
            "next_page_token",
            b"next_page_token",
            "page_size",
            b"page_size",
            "query",
            b"query",
        ],
    ) -> None: ...

global___ListStreamsInput = ListStreamsInput

class StreamListEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    run_id: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        run_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "run_id", b"run_id", "stream_id", b"stream_id"
        ],
    ) -> None: ...

global___StreamListEntry = StreamListEntry

class ListStreamsOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAMS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def streams(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___StreamListEntry
    ]: ...
    next_page_token: builtins.bytes
    def __init__(
        self,
        *,
        streams: collections.abc.Iterable[global___StreamListEntry] | None = ...,
        next_page_token: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "next_page_token", b"next_page_token", "streams", b"streams"
        ],
    ) -> None: ...

global___ListStreamsOutput = ListStreamsOutput

class ListStreamsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___ListStreamsInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___ListStreamsInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___ListStreamsRequest = ListStreamsRequest

class ListStreamsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___ListStreamsOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___ListStreamsOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___ListStreamsResponse = ListStreamsResponse

class DeleteStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAMESPACE_ID_FIELD_NUMBER: builtins.int
    FRONTEND_REQUEST_FIELD_NUMBER: builtins.int
    namespace_id: builtins.str
    @property
    def frontend_request(self) -> global___DeleteStreamInput: ...
    def __init__(
        self,
        *,
        namespace_id: builtins.str = ...,
        frontend_request: global___DeleteStreamInput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["frontend_request", b"frontend_request"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_request", b"frontend_request", "namespace_id", b"namespace_id"
        ],
    ) -> None: ...

global___DeleteStreamRequest = DeleteStreamRequest

class DeleteStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONTEND_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def frontend_response(self) -> global___DeleteStreamOutput: ...
    def __init__(
        self,
        *,
        frontend_response: global___DeleteStreamOutput | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "frontend_response", b"frontend_response"
        ],
    ) -> None: ...

global___DeleteStreamResponse = DeleteStreamResponse
