# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from temporalio.api.streamservice.v1 import (
    request_response_pb2 as temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2,
)


class StreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/CreateStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamResponse.FromString,
        )
        self.AddMessages = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AddMessages",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesResponse.FromString,
        )
        self.FinishWriting = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/FinishWriting",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingResponse.FromString,
        )
        self.SubscribeWorkflow = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/SubscribeWorkflow",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowResponse.FromString,
        )
        self.PollMessages = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/PollMessages",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesResponse.FromString,
        )
        self.DescribeStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DescribeStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamResponse.FromString,
        )
        self.PollWorkflowMessages = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/PollWorkflowMessages",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesResponse.FromString,
        )
        self.DescribeWorkflowStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DescribeWorkflowStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamResponse.FromString,
        )
        self.AddWorkflowMessages = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AddWorkflowMessages",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesResponse.FromString,
        )
        self.RegisterStreamConsumer = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/RegisterStreamConsumer",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerResponse.FromString,
        )
        self.AdvanceConsumerHead = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AdvanceConsumerHead",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadResponse.FromString,
        )
        self.CloseStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/CloseStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamResponse.FromString,
        )
        self.TruncateStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/TruncateStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamResponse.FromString,
        )
        self.ListStreams = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/ListStreams",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsResponse.FromString,
        )
        self.DeleteStream = channel.unary_unary(
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DeleteStream",
            request_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamRequest.SerializeToString,
            response_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamResponse.FromString,
        )


class StreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FinishWriting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubscribeWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PollMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DescribeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PollWorkflowMessages(self, request, context):
        """Routed on the owner, because the stream it reads has no id of its own."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DescribeWorkflowStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddWorkflowMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterStreamConsumer(self, request, context):
        """Internal. History calls these on itself to reach a shard it does not own,
        which is the only way a step that spans two executions can work on a
        cluster with more than one history host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdvanceConsumerHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TruncateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListStreams(self, request, context):
        """Served on the frontend only: it queries visibility rather than a stream,
        so there is no business ID to route on and nothing for a shard to answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateStream": grpc.unary_unary_rpc_method_handler(
            servicer.CreateStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamResponse.SerializeToString,
        ),
        "AddMessages": grpc.unary_unary_rpc_method_handler(
            servicer.AddMessages,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesResponse.SerializeToString,
        ),
        "FinishWriting": grpc.unary_unary_rpc_method_handler(
            servicer.FinishWriting,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingResponse.SerializeToString,
        ),
        "SubscribeWorkflow": grpc.unary_unary_rpc_method_handler(
            servicer.SubscribeWorkflow,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowResponse.SerializeToString,
        ),
        "PollMessages": grpc.unary_unary_rpc_method_handler(
            servicer.PollMessages,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesResponse.SerializeToString,
        ),
        "DescribeStream": grpc.unary_unary_rpc_method_handler(
            servicer.DescribeStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamResponse.SerializeToString,
        ),
        "PollWorkflowMessages": grpc.unary_unary_rpc_method_handler(
            servicer.PollWorkflowMessages,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesResponse.SerializeToString,
        ),
        "DescribeWorkflowStream": grpc.unary_unary_rpc_method_handler(
            servicer.DescribeWorkflowStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamResponse.SerializeToString,
        ),
        "AddWorkflowMessages": grpc.unary_unary_rpc_method_handler(
            servicer.AddWorkflowMessages,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesResponse.SerializeToString,
        ),
        "RegisterStreamConsumer": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterStreamConsumer,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerResponse.SerializeToString,
        ),
        "AdvanceConsumerHead": grpc.unary_unary_rpc_method_handler(
            servicer.AdvanceConsumerHead,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadResponse.SerializeToString,
        ),
        "CloseStream": grpc.unary_unary_rpc_method_handler(
            servicer.CloseStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamResponse.SerializeToString,
        ),
        "TruncateStream": grpc.unary_unary_rpc_method_handler(
            servicer.TruncateStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamResponse.SerializeToString,
        ),
        "ListStreams": grpc.unary_unary_rpc_method_handler(
            servicer.ListStreams,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsResponse.SerializeToString,
        ),
        "DeleteStream": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteStream,
            request_deserializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamRequest.FromString,
            response_serializer=temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "temporal.server.chasm.lib.stream.proto.v1.StreamService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class StreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/CreateStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CreateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AddMessages",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FinishWriting(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/FinishWriting",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.FinishWritingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubscribeWorkflow(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/SubscribeWorkflow",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.SubscribeWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PollMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/PollMessages",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DescribeStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DescribeStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PollWorkflowMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/PollWorkflowMessages",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.PollWorkflowMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DescribeWorkflowStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DescribeWorkflowStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DescribeWorkflowStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddWorkflowMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AddWorkflowMessages",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AddWorkflowMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RegisterStreamConsumer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/RegisterStreamConsumer",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.RegisterStreamConsumerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AdvanceConsumerHead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/AdvanceConsumerHead",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.AdvanceConsumerHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CloseStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/CloseStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.CloseStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TruncateStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/TruncateStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.TruncateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListStreams(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/ListStreams",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.ListStreamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/temporal.server.chasm.lib.stream.proto.v1.StreamService/DeleteStream",
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamRequest.SerializeToString,
            temporalio_dot_api_dot_stream_dot_v1_dot_request__response__pb2.DeleteStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
