# Generated by nexgen v0.2.8. DO NOT EDIT!

from __future__ import annotations

import typing

if typing.TYPE_CHECKING:
    from temporalio.workflow import NexusOperationHandle

from ..models import (
    AttachStreamCallbackRequest,
    AttachStreamCallbackResponse,
    CallbackNexus,
    StreamReference,
    Timestamp,
)


async def _attach_stream_callback(
    request: AttachStreamCallbackRequest,
) -> NexusOperationHandle[AttachStreamCallbackResponse,]:
    from temporalio.workflow import create_nexus_client

    nexus_client = create_nexus_client(
        service="temporal.api.workflowservice.v1.WorkflowService",
        endpoint="__temporal_system",
    )
    return await nexus_client.start_operation(
        operation="AttachStreamCallback",
        input=request,
        output_type=AttachStreamCallbackResponse,
    )


async def attach_stream_callback(
    *,
    stream_ref: StreamReference | None = None,
    request_id: str,
    callback: CallbackNexus | None = None,
    operation_token: str,
    start_time: Timestamp | None = None,
) -> NexusOperationHandle[AttachStreamCallbackResponse,]:
    request = AttachStreamCallbackRequest(
        stream_ref=stream_ref,
        request_id=request_id,
        callback=callback,
        operation_token=operation_token,
        start_time=start_time,
    )
    return await _attach_stream_callback(request)
