# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/stream/v1/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporalio.api.common.v1 import message_pb2 as temporal_dot_api_dot_common_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$temporal/api/stream/v1/message.proto\x12\x16temporal.api.stream.v1\x1a$temporal/api/common/v1/message.proto\"\xfe\x01\n\rStreamMessage\x12-\n\x04\x62ody\x18\x01 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload\x12\x45\n\x08metadata\x18\x02 \x03(\x0b\x32\x33.temporal.api.stream.v1.StreamMessage.MetadataEntry\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x16\n\x0etopic_sequence\x18\x04 \x01(\x03\x1aP\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.temporal.api.common.v1.Payload:\x02\x38\x01\"\xbb\x01\n\x0bStreamSlice\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x13\n\x0b\x66rom_offset\x18\x03 \x01(\x03\x12\x11\n\tto_offset\x18\x04 \x01(\x03\x12\x37\n\x08messages\x18\x05 \x03(\x0b\x32%.temporal.api.stream.v1.StreamMessage\x12(\n workflow_task_completed_event_id\x18\x06 \x01(\x03\"I\n\x0cStreamCursor\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66rom_offset\x18\x02 \x01(\x03\x12\x11\n\tto_offset\x18\x03 \x01(\x03\x42\x89\x01\n\x19io.temporal.api.stream.v1B\x0cMessageProtoP\x01Z#go.temporal.io/api/stream/v1;stream\xaa\x02\x18Temporalio.Api.Stream.V1\xea\x02\x1bTemporalio::Api::Stream::V1b\x06proto3')



_STREAMMESSAGE = DESCRIPTOR.message_types_by_name['StreamMessage']
_STREAMMESSAGE_METADATAENTRY = _STREAMMESSAGE.nested_types_by_name['MetadataEntry']
_STREAMSLICE = DESCRIPTOR.message_types_by_name['StreamSlice']
_STREAMCURSOR = DESCRIPTOR.message_types_by_name['StreamCursor']
StreamMessage = _reflection.GeneratedProtocolMessageType('StreamMessage', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _STREAMMESSAGE_METADATAENTRY,
    '__module__' : 'temporalio.api.stream.v1.message_pb2'
    # @@protoc_insertion_point(class_scope:temporal.api.stream.v1.StreamMessage.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _STREAMMESSAGE,
  '__module__' : 'temporalio.api.stream.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.stream.v1.StreamMessage)
  })
_sym_db.RegisterMessage(StreamMessage)
_sym_db.RegisterMessage(StreamMessage.MetadataEntry)

StreamSlice = _reflection.GeneratedProtocolMessageType('StreamSlice', (_message.Message,), {
  'DESCRIPTOR' : _STREAMSLICE,
  '__module__' : 'temporalio.api.stream.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.stream.v1.StreamSlice)
  })
_sym_db.RegisterMessage(StreamSlice)

StreamCursor = _reflection.GeneratedProtocolMessageType('StreamCursor', (_message.Message,), {
  'DESCRIPTOR' : _STREAMCURSOR,
  '__module__' : 'temporalio.api.stream.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.stream.v1.StreamCursor)
  })
_sym_db.RegisterMessage(StreamCursor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031io.temporal.api.stream.v1B\014MessageProtoP\001Z#go.temporal.io/api/stream/v1;stream\252\002\030Temporalio.Api.Stream.V1\352\002\033Temporalio::Api::Stream::V1'
  _STREAMMESSAGE_METADATAENTRY._options = None
  _STREAMMESSAGE_METADATAENTRY._serialized_options = b'8\001'
  _STREAMMESSAGE._serialized_start=103
  _STREAMMESSAGE._serialized_end=357
  _STREAMMESSAGE_METADATAENTRY._serialized_start=277
  _STREAMMESSAGE_METADATAENTRY._serialized_end=357
  _STREAMSLICE._serialized_start=360
  _STREAMSLICE._serialized_end=547
  _STREAMCURSOR._serialized_start=549
  _STREAMCURSOR._serialized_end=622
# @@protoc_insertion_point(module_scope)
