"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StreamOwnerKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StreamOwnerKindEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
        _StreamOwnerKind.ValueType
    ],
    builtins.type,
):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STREAM_OWNER_KIND_UNSPECIFIED: _StreamOwnerKind.ValueType  # 0
    STREAM_OWNER_KIND_WORKFLOW: _StreamOwnerKind.ValueType  # 1
    """A Workflow owns the stream. It closes when the Workflow's run chain closes."""

class StreamOwnerKind(_StreamOwnerKind, metaclass=_StreamOwnerKindEnumTypeWrapper):
    """What owns a stream. The owner decides when the stream closes."""

STREAM_OWNER_KIND_UNSPECIFIED: StreamOwnerKind.ValueType  # 0
STREAM_OWNER_KIND_WORKFLOW: StreamOwnerKind.ValueType  # 1
"""A Workflow owns the stream. It closes when the Workflow's run chain closes."""
global___StreamOwnerKind = StreamOwnerKind
