"""Generated protobuf models for the stream record envelope.

.. warning::
    This package is experimental and may change in future versions.

The modules under ``v1`` are generated by ``scripts/gen_protos.py`` and
rewritten on every run, so this note lives here rather than in them.
"""
