# Generated by nexgen v0.2.8. DO NOT EDIT!

from __future__ import annotations

import asyncio
import dataclasses
import json
import time
import typing
import urllib.error
import urllib.request

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
    StreamRef,
    _AppendInputTransferTypeConverter,
    _AppendOutputTransferTypeConverter,
    _ReadInputTransferTypeConverter,
    _ReadOutputTransferTypeConverter,
)


class HTTPStatusError(RuntimeError):
    """An answer from the ingress that is not a synchronous result.

    It carries the status so a caller can tell a refusal apart from an answer
    another attempt could still get.
    """

    def __init__(
        self, url: str, status: int, detail: str, retryable: bool | None = None
    ) -> None:
        super().__init__(f"{url} failed ({status}): {detail}")
        # Annotated explicitly: a target's strict type checker asks for it on a
        # class it cannot prove closed.
        self.url: str = url
        self.status: int = status
        self.detail: str = detail
        self._retryable: bool | None = retryable

    @property
    def retryable(self) -> bool:
        """Whether the same request could answer differently.

        The handler's ``Nexus-Request-Retryable`` header decides when it is
        set. Otherwise too many requests and the server-side failures are the
        endpoint's own transient conditions; every other status is about this
        request, and repeating it changes nothing.
        """
        if self._retryable is not None:
            return self._retryable
        return self.status == 429 or self.status >= 500


def _retryable_header(headers: typing.Any) -> bool | None:
    value = headers.get("Nexus-Request-Retryable") if headers is not None else None
    if value is None:
        return None
    return str(value).strip().lower() == "true"


def _post(url: str, body: bytes, headers: dict[str, str], timeout: float) -> bytes:
    request = urllib.request.Request(
        url,
        data=body,
        headers={
            "Content-Type": "application/json",
            # Tells the handler how long this caller waits, so it can cut a
            # long poll short instead of being cut off.
            "Request-Timeout": f"{int(timeout * 1000)}ms",
            **headers,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status = typing.cast("int", response.status)
            answer = typing.cast("bytes", response.read())
            retryable = _retryable_header(response.headers)
    except urllib.error.HTTPError as error:
        detail = error.read().decode(errors="replace")
        raise HTTPStatusError(
            url, error.code, detail, _retryable_header(error.headers)
        ) from error
    # A 201 means the handler started the operation asynchronously and answered
    # with a token, which this caller cannot read as the operation's result.
    if status not in (200, 204):
        raise HTTPStatusError(url, status, answer.decode(errors="replace"), retryable)
    return answer


_LONG_POLL_MIN_BACKOFF = 0.05
_LONG_POLL_MAX_BACKOFF = 2.0


async def _long_poll_pause(backoff: float, end: float) -> None:
    """Waits out a backoff without running past the read's own deadline."""
    remaining = end - time.monotonic()
    delay = min(backoff, remaining)
    if delay > 0:
        await asyncio.sleep(delay)


def _long_poll_next_backoff(backoff: float) -> float:
    return min(backoff * 2, _LONG_POLL_MAX_BACKOFF)


class TemporalStreamsHttpClient:
    """Appends to and reads from streams through one Nexus endpoint, so the store
    behind it stays the endpoint's business and an operator can change it without
    touching callers. An append carries one batch and a read answers with a batch,
    because a Nexus operation per record costs too much for token streams. A
    record crosses as the serialized temporal.sdk.streams.v1.StreamRecord, the
    bytes every store keeps, so a caller in any language decodes it with that
    proto alone.

    Every method posts to ``{base_url}/{operation}``, so ``base_url`` is the
    service's address on the Nexus HTTP ingress, up to but not including the
    operation name.
    """

    def __init__(
        self,
        base_url: str,
        *,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._base_url: str = base_url.rstrip("/")
        self._headers: dict[str, str] = dict(headers or {})
        self._timeout: float = timeout

    def _poll_budget(self, remaining: float) -> float:
        """How long one attempt may ask the endpoint to park, in seconds.

        Asking for longer than the transport will wait is a socket timeout
        dressed as a long poll, so the ask leaves the answer room to come back
        inside this client's own timeout.
        """
        return max(0.001, min(remaining, self._timeout * 0.9))

    async def append(
        self,
        request: AppendInput,
    ) -> AppendOutput:
        """Write one batch as one producer attempt, or finish the producer. The store
        numbers the batch from sequence and deduplicates a retry: a repeat of the
        producer attempt's newest batch with the same content answers with where
        the original landed and writes nothing. A sequence already used with other
        content, or below the newest one the store holds for the attempt, is
        refused. Supersession records are never written: a reader synthesizes them
        from the attempts it observes.
        """
        wire: typing.Any = _AppendInputTransferTypeConverter().to_transfer_type(request)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/append",
            body,
            self._headers,
            self._timeout,
        )
        if not raw:
            raise ValueError("append answered with an empty body")
        answer: typing.Any = json.loads(raw)
        return _AppendOutputTransferTypeConverter().from_transfer_type(
            answer, AppendOutput
        )

    async def read(
        self,
        request: ReadInput,
    ) -> ReadOutput:
        """Answer with the records after the caller's cursor. The call waits until it
        has max_records records or wait_ms passes, whichever comes first, and
        answers with what it collected. It says when the stream has ended for the
        reader, so the caller can stop.
        """
        wire: typing.Any = _ReadInputTransferTypeConverter().to_transfer_type(request)
        body = json.dumps(wire).encode()
        raw = await asyncio.to_thread(
            _post,
            f"{self._base_url}/read",
            body,
            self._headers,
            self._timeout,
        )
        if not raw:
            raise ValueError("read answered with an empty body")
        answer: typing.Any = json.loads(raw)
        return _ReadOutputTransferTypeConverter().from_transfer_type(answer, ReadOutput)

    async def read_until_records(
        self,
        request: ReadInput,
        *,
        deadline: float,
    ) -> ReadOutput:
        """Calls ``read`` until it answers with something, or until ``deadline``.

        Each attempt sets ``wait_ms`` from the budget left, so the endpoint parks
        for the caller instead of the caller spinning. The first answer whose
        ``records`` is non-empty, or whose ``done`` is true, is returned. When the
        deadline passes first, the last answer is returned, which still carries
        the caller's resume position.

        ``deadline`` is the whole budget in seconds. The single-shot method stays
        available for a caller that wants one attempt.
        """
        end = time.monotonic() + deadline
        answer: ReadOutput | None = None
        backoff = _LONG_POLL_MIN_BACKOFF
        while True:
            wait = self._poll_budget(end - time.monotonic())
            wait_ms = int(wait * 1000)
            wait_ms = min(wait_ms, 60000)
            wait_ms = max(wait_ms, 0)
            wait = wait_ms / 1000
            attempt = dataclasses.replace(request, wait_ms=wait_ms)
            started = time.monotonic()
            try:
                answer = await self.read(attempt)
            except HTTPStatusError as error:
                if not error.retryable or time.monotonic() >= end:
                    raise
                await _long_poll_pause(backoff, end)
                backoff = _long_poll_next_backoff(backoff)
                continue
            if answer.records or answer.done:
                return answer
            if time.monotonic() >= end:
                return answer
            if time.monotonic() - started < wait / 2:
                await _long_poll_pause(backoff, end)
                backoff = _long_poll_next_backoff(backoff)
            else:
                backoff = _LONG_POLL_MIN_BACKOFF

    def stream(
        self,
        *,
        stream: StreamRef,
    ) -> "StreamHandle":
        """A ``StreamHandle`` bound to ``stream``."""
        return StreamHandle(
            self,
            stream=stream,
        )

    def stream_producer(
        self,
        *,
        stream: StreamRef,
        producer_id: str,
        attempt: int,
    ) -> "StreamProducer":
        """A ``StreamProducer`` bound to ``stream``, ``producer_id``, ``attempt``."""
        return StreamProducer(
            self,
            stream=stream,
            producer_id=producer_id,
            attempt=attempt,
        )


class StreamHandle:
    """Binds ``stream`` for the temporal.sdk.streams.v1.TemporalStreams service.

    Every method posts through the ``TemporalStreamsHttpClient`` it was built from
    with the bound members filled in, so a caller states a stream's identity once.
    The flat caller stays available for a call that spells every member out.
    """

    def __init__(
        self,
        client: TemporalStreamsHttpClient,
        *,
        stream: StreamRef,
    ) -> None:
        self._client: TemporalStreamsHttpClient = client
        self._stream: StreamRef = stream

    async def append(
        self,
        *,
        producer_id: str,
        attempt: int,
        sequence: int,
        payloads: list[bytes] | None = None,
        finish: bool | None = None,
    ) -> AppendOutput:
        """Write one batch as one producer attempt, or finish the producer. The store
        numbers the batch from sequence and deduplicates a retry: a repeat of the
        producer attempt's newest batch with the same content answers with where
        the original landed and writes nothing. A sequence already used with other
        content, or below the newest one the store holds for the attempt, is
        refused. Supersession records are never written: a reader synthesizes them
        from the attempts it observes.

        This handle supplies ``stream``; the flat caller's ``append`` takes it
        spelled out.
        """
        return await self._client.append(
            AppendInput(
                stream=self._stream,
                producer_id=producer_id,
                attempt=attempt,
                sequence=sequence,
                payloads=payloads,
                finish=finish,
            ),
        )

    async def read(
        self,
        *,
        after_token: str | None = None,
        max_records: int | None = None,
        wait_ms: int | None = None,
        latest_only: bool | None = None,
    ) -> ReadOutput:
        """Answer with the records after the caller's cursor. The call waits until it
        has max_records records or wait_ms passes, whichever comes first, and
        answers with what it collected. It says when the stream has ended for the
        reader, so the caller can stop.

        This handle supplies ``stream``; the flat caller's ``read`` takes it
        spelled out.
        """
        return await self._client.read(
            ReadInput(
                stream=self._stream,
                after_token=after_token,
                max_records=max_records,
                wait_ms=wait_ms,
                latest_only=latest_only,
            ),
        )

    async def read_until_records(
        self,
        *,
        after_token: str | None = None,
        max_records: int | None = None,
        latest_only: bool | None = None,
        deadline: float,
    ) -> ReadOutput:
        """Calls ``read`` until it answers with something, or until ``deadline``.

        Each attempt sets ``wait_ms`` from the budget left, so the endpoint parks
        for the caller instead of the caller spinning. The first answer whose
        ``records`` is non-empty, or whose ``done`` is true, is returned. When the
        deadline passes first, the last answer is returned, which still carries
        the caller's resume position.

        ``deadline`` is the whole budget in seconds. The single-shot method stays
        available for a caller that wants one attempt.

        This handle supplies ``stream``; the flat caller's ``read_until_records``
        takes it spelled out.
        """
        return await self._client.read_until_records(
            ReadInput(
                stream=self._stream,
                after_token=after_token,
                max_records=max_records,
                latest_only=latest_only,
            ),
            deadline=deadline,
        )

    def producer(
        self,
        *,
        producer_id: str,
        attempt: int,
    ) -> "StreamProducer":
        """A ``StreamProducer`` bound to ``stream``, ``producer_id``, ``attempt``:
        this handle's own members and the ones given here.
        """
        return StreamProducer(
            self._client,
            stream=self._stream,
            producer_id=producer_id,
            attempt=attempt,
        )


class StreamProducer:
    """Binds ``stream``, ``producer_id``, ``attempt`` for the
    temporal.sdk.streams.v1.TemporalStreams service.

    Every method posts through the ``TemporalStreamsHttpClient`` it was built from
    with the bound members filled in, so a caller states a stream's identity once.
    The flat caller stays available for a call that spells every member out.
    """

    def __init__(
        self,
        client: TemporalStreamsHttpClient,
        *,
        stream: StreamRef,
        producer_id: str,
        attempt: int,
    ) -> None:
        self._client: TemporalStreamsHttpClient = client
        self._stream: StreamRef = stream
        self._producer_id: str = producer_id
        self._attempt: int = attempt

    async def append(
        self,
        *,
        sequence: int,
        payloads: list[bytes] | None = None,
        finish: bool | None = None,
    ) -> AppendOutput:
        """Write one batch as one producer attempt, or finish the producer. The store
        numbers the batch from sequence and deduplicates a retry: a repeat of the
        producer attempt's newest batch with the same content answers with where
        the original landed and writes nothing. A sequence already used with other
        content, or below the newest one the store holds for the attempt, is
        refused. Supersession records are never written: a reader synthesizes them
        from the attempts it observes.

        This handle supplies ``stream``, ``producer_id``, ``attempt``; the flat
        caller's ``append`` takes them spelled out.
        """
        return await self._client.append(
            AppendInput(
                stream=self._stream,
                producer_id=self._producer_id,
                attempt=self._attempt,
                sequence=sequence,
                payloads=payloads,
                finish=finish,
            ),
        )
