# Generated by nexgen v0.2.8. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing

import typing_extensions

import temporalio.contrib.streams
import temporalio.converter
import temporalio.exceptions

from ._definitions import (
    Violation,
    _collect,
    _format_base64,
    _member_path,
    _parse_base64,
    _parse_spec_integer,
    _transfer_type_convertible,
)

_APPEND_OUTPUT_DECLARED: frozenset[str] = frozenset({"cursor"})


_READ_OUTPUT_DECLARED: frozenset[str] = frozenset({"records", "next_token", "done"})


_RECORD_WIRE_DECLARED: frozenset[str] = frozenset({"token", "record"})


class _AppendInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendInput"]
    ) -> "AppendInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        stream_value: StreamRef = typing.cast("typing.Any", None)
        if "stream" not in raw or raw["stream"] is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_value_raw = raw["stream"]
            try:
                stream_value = _StreamRefTransferTypeConverter().from_transfer_type(
                    stream_value_raw, StreamRef
                )
            except temporalio.exceptions.ApplicationError as error:
                _collect(violations, "stream", error)

        producer_id_value: str = typing.cast("typing.Any", None)
        if "producer_id" not in raw or raw["producer_id"] is None:
            violations.append(Violation(path="producer_id", reason="required"))
        else:
            producer_id_value_raw = raw["producer_id"]
            if not isinstance(producer_id_value_raw, str):
                violations.append(
                    Violation(path="producer_id", reason="expected string")
                )
            else:
                producer_id_value = producer_id_value_raw

        attempt_value: int = typing.cast("typing.Any", None)
        if "attempt" not in raw or raw["attempt"] is None:
            violations.append(Violation(path="attempt", reason="required"))
        else:
            attempt_value_raw = raw["attempt"]
            attempt_value_parsed = _parse_spec_integer(
                attempt_value_raw, "attempt", violations
            )
            if attempt_value_parsed is not None:
                attempt_value = attempt_value_parsed
                if attempt_value < 1:
                    violations.append(
                        Violation(
                            path="attempt", reason=f"must be >= 1, got {attempt_value}"
                        )
                    )

        sequence_value: int = typing.cast("typing.Any", None)
        if "sequence" not in raw or raw["sequence"] is None:
            violations.append(Violation(path="sequence", reason="required"))
        else:
            sequence_value_raw = raw["sequence"]
            sequence_value_parsed = _parse_spec_integer(
                sequence_value_raw, "sequence", violations
            )
            if sequence_value_parsed is not None:
                sequence_value = sequence_value_parsed
                if sequence_value < 1:
                    violations.append(
                        Violation(
                            path="sequence",
                            reason=f"must be >= 1, got {sequence_value}",
                        )
                    )

        payloads_value: list[bytes] | None = None
        if "payloads" in raw:
            payloads_value_raw = raw["payloads"]
            if payloads_value_raw is None:
                violations.append(
                    Violation(path="payloads", reason="explicit null not allowed")
                )
            else:
                if not isinstance(payloads_value_raw, list):
                    violations.append(
                        Violation(path="payloads", reason="expected array")
                    )
                else:
                    payloads_value_list: list[bytes] = []
                    for payloads_value_index, payloads_value_element in enumerate(
                        typing.cast("list[typing.Any]", payloads_value_raw)
                    ):
                        payloads_value_item_path = f"payloads[{payloads_value_index}]"
                        payloads_value_item_violation_count = len(violations)
                        payloads_value_item: bytes = typing.cast("typing.Any", None)
                        if not isinstance(payloads_value_element, str):
                            violations.append(
                                Violation(
                                    path=payloads_value_item_path,
                                    reason="expected string",
                                )
                            )
                        else:
                            payloads_value_item_parsed = _parse_base64(
                                payloads_value_element,
                                payloads_value_item_path,
                                violations,
                            )
                            if payloads_value_item_parsed is not None:
                                payloads_value_item = payloads_value_item_parsed
                        if len(violations) == payloads_value_item_violation_count:
                            payloads_value_list.append(payloads_value_item)
                    payloads_value = payloads_value_list

        finish_value: bool | None = None
        if "finish" in raw:
            finish_value_raw = raw["finish"]
            if finish_value_raw is None:
                violations.append(
                    Violation(path="finish", reason="explicit null not allowed")
                )
            else:
                if not isinstance(finish_value_raw, bool):
                    violations.append(
                        Violation(path="finish", reason="expected boolean")
                    )
                else:
                    finish_value = finish_value_raw

        for key in raw:
            if (
                key != "stream"
                and key != "producer_id"
                and key != "attempt"
                and key != "sequence"
                and key != "payloads"
                and key != "finish"
            ):
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendInput(
            stream=stream_value,
            producer_id=producer_id_value,
            attempt=attempt_value,
            sequence=sequence_value,
            payloads=payloads_value,
            finish=finish_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendInput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, AppendInput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        stream_value: typing.Any = runtime_value.stream
        if stream_value is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_violation_count = len(violations)
            if len(violations) == stream_violation_count:
                try:
                    out["stream"] = _StreamRefTransferTypeConverter().to_transfer_type(
                        stream_value
                    )
                except temporalio.exceptions.ApplicationError as error:
                    _collect(violations, "stream", error)
        producer_id_value: typing.Any = runtime_value.producer_id
        if producer_id_value is None:
            violations.append(Violation(path="producer_id", reason="required"))
        else:
            if not (isinstance(producer_id_value, str)):
                violations.append(
                    Violation(path="producer_id", reason="expected string")
                )
            out["producer_id"] = producer_id_value
        attempt_value: typing.Any = runtime_value.attempt
        if attempt_value is None:
            violations.append(Violation(path="attempt", reason="required"))
        else:
            if not (
                not isinstance(attempt_value, bool)
                and (
                    isinstance(attempt_value, int)
                    or (isinstance(attempt_value, float) and attempt_value.is_integer())
                )
            ):
                violations.append(Violation(path="attempt", reason="expected integer"))
            else:
                if abs(attempt_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="attempt", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if attempt_value < 1:
                    violations.append(
                        Violation(
                            path="attempt", reason=f"must be >= 1, got {attempt_value}"
                        )
                    )
            out["attempt"] = attempt_value
        sequence_value: typing.Any = runtime_value.sequence
        if sequence_value is None:
            violations.append(Violation(path="sequence", reason="required"))
        else:
            if not (
                not isinstance(sequence_value, bool)
                and (
                    isinstance(sequence_value, int)
                    or (
                        isinstance(sequence_value, float)
                        and sequence_value.is_integer()
                    )
                )
            ):
                violations.append(Violation(path="sequence", reason="expected integer"))
            else:
                if abs(sequence_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="sequence", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if sequence_value < 1:
                    violations.append(
                        Violation(
                            path="sequence",
                            reason=f"must be >= 1, got {sequence_value}",
                        )
                    )
            out["sequence"] = sequence_value
        payloads_value: typing.Any = runtime_value.payloads
        if payloads_value is not None:
            payloads_violation_count = len(violations)
            if not (isinstance(payloads_value, list)):
                violations.append(Violation(path="payloads", reason="expected array"))
            else:
                checked_array_8 = typing.cast("list[typing.Any]", payloads_value)
                for item_index_8, item_element_8 in enumerate(checked_array_8):
                    if not (isinstance(item_element_8, bytes)):
                        violations.append(
                            Violation(
                                path=f"payloads[{item_index_8}]",
                                reason="expected bytes",
                            )
                        )
            if len(violations) == payloads_violation_count:
                payloads_checked = typing.cast("list[typing.Any]", payloads_value)
                out["payloads"] = [
                    _format_base64(element) for element in payloads_checked
                ]
        finish_value: typing.Any = runtime_value.finish
        if finish_value is not None:
            if not (isinstance(finish_value, bool)):
                violations.append(Violation(path="finish", reason="expected boolean"))
            out["finish"] = finish_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendInput:
    """One append call: who writes, where, and what."""

    stream: StreamRef

    producer_id: str
    """Names the writer across its retries, so the store can deduplicate a retry and a
    reader can tell a retry from a new attempt. Never empty.
    """

    attempt: int
    """The producer attempt this call writes. A higher attempt supersedes a lower one, and
    its sequence starts again at one.
    """

    sequence: int
    """The sequence of the first record this call writes. Records of an attempt are
    numbered from one with no gaps, so it continues where the attempt's previous call
    ended, or repeats that call's sequence for a retry.
    """

    payloads: list[bytes] | None = None
    """The record bodies, in order, each a serialized temporal.api.common.v1.Payload. The
    caller's payload codec has already run on them, so the endpoint never sees plaintext
    a codec protects. A retry resends the original call's bytes: the store compares the
    bodies as they arrive, so a codec that encodes with a fresh nonce would make a
    re-encoded retry look like other content. Empty on a call that finishes.
    """

    finish: bool | None = None
    """Write FINISH for this producer at sequence: it writes nothing more on the topic. A
    finishing call carries no payloads, so every call is one store write and a retry of
    it is deduplicated whole. Says nothing about the producer's outcome.
    """


class _AppendOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendOutput"]
    ) -> "AppendOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        cursor_value: str = typing.cast("typing.Any", None)
        if "cursor" not in raw or raw["cursor"] is None:
            violations.append(Violation(path="cursor", reason="required"))
        else:
            cursor_value_raw = raw["cursor"]
            if not isinstance(cursor_value_raw, str):
                violations.append(Violation(path="cursor", reason="expected string"))
            else:
                cursor_value = cursor_value_raw

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _APPEND_OUTPUT_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendOutput(
            cursor=cursor_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendOutput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, AppendOutput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        cursor_value: typing.Any = runtime_value.cursor
        if cursor_value is None:
            violations.append(Violation(path="cursor", reason="required"))
        else:
            if not (isinstance(cursor_value, str)):
                violations.append(Violation(path="cursor", reason="expected string"))
            out["cursor"] = cursor_value
        additional_properties_value: typing.Any = runtime_value.additional_properties
        if not isinstance(additional_properties_value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        checked_additional_properties = typing.cast(
            "dict[str, typing.Any]", additional_properties_value
        )
        for key, entry in checked_additional_properties.items():
            path = _member_path(key)
            if key in _APPEND_OUTPUT_DECLARED:
                violations.append(
                    Violation(
                        path=path,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendOutput:
    """Where the append landed."""

    cursor: str
    """The cursor of the last record this call wrote, or of the original's last record when
    the call was a deduplicated retry.
    """

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )


class _ReadInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadInput"]
    ) -> "ReadInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        stream_value: StreamRef = typing.cast("typing.Any", None)
        if "stream" not in raw or raw["stream"] is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_value_raw = raw["stream"]
            try:
                stream_value = _StreamRefTransferTypeConverter().from_transfer_type(
                    stream_value_raw, StreamRef
                )
            except temporalio.exceptions.ApplicationError as error:
                _collect(violations, "stream", error)

        after_token_value: str | None = None
        if "after_token" in raw:
            after_token_value_raw = raw["after_token"]
            if after_token_value_raw is None:
                violations.append(
                    Violation(path="after_token", reason="explicit null not allowed")
                )
            else:
                if not isinstance(after_token_value_raw, str):
                    violations.append(
                        Violation(path="after_token", reason="expected string")
                    )
                else:
                    after_token_value = after_token_value_raw

        max_records_value: int | None = None
        if "max_records" in raw:
            max_records_value_raw = raw["max_records"]
            if max_records_value_raw is None:
                violations.append(
                    Violation(path="max_records", reason="explicit null not allowed")
                )
            else:
                max_records_value_parsed = _parse_spec_integer(
                    max_records_value_raw, "max_records", violations
                )
                if max_records_value_parsed is not None:
                    max_records_value = max_records_value_parsed
                    if max_records_value < 1:
                        violations.append(
                            Violation(
                                path="max_records",
                                reason=f"must be >= 1, got {max_records_value}",
                            )
                        )
                    if max_records_value > 1000:
                        violations.append(
                            Violation(
                                path="max_records",
                                reason=f"must be <= 1000, got {max_records_value}",
                            )
                        )

        wait_ms_value: int | None = None
        if "wait_ms" in raw:
            wait_ms_value_raw = raw["wait_ms"]
            if wait_ms_value_raw is None:
                violations.append(
                    Violation(path="wait_ms", reason="explicit null not allowed")
                )
            else:
                wait_ms_value_parsed = _parse_spec_integer(
                    wait_ms_value_raw, "wait_ms", violations
                )
                if wait_ms_value_parsed is not None:
                    wait_ms_value = wait_ms_value_parsed
                    if wait_ms_value < 0:
                        violations.append(
                            Violation(
                                path="wait_ms",
                                reason=f"must be >= 0, got {wait_ms_value}",
                            )
                        )
                    if wait_ms_value > 60000:
                        violations.append(
                            Violation(
                                path="wait_ms",
                                reason=f"must be <= 60000, got {wait_ms_value}",
                            )
                        )

        latest_only_value: bool | None = None
        if "latest_only" in raw:
            latest_only_value_raw = raw["latest_only"]
            if latest_only_value_raw is None:
                violations.append(
                    Violation(path="latest_only", reason="explicit null not allowed")
                )
            else:
                if not isinstance(latest_only_value_raw, bool):
                    violations.append(
                        Violation(path="latest_only", reason="expected boolean")
                    )
                else:
                    latest_only_value = latest_only_value_raw

        for key in raw:
            if (
                key != "stream"
                and key != "after_token"
                and key != "max_records"
                and key != "wait_ms"
                and key != "latest_only"
            ):
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadInput(
            stream=stream_value,
            after_token=after_token_value,
            max_records=max_records_value,
            wait_ms=wait_ms_value,
            latest_only=latest_only_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadInput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, ReadInput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        stream_value: typing.Any = runtime_value.stream
        if stream_value is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_violation_count = len(violations)
            if len(violations) == stream_violation_count:
                try:
                    out["stream"] = _StreamRefTransferTypeConverter().to_transfer_type(
                        stream_value
                    )
                except temporalio.exceptions.ApplicationError as error:
                    _collect(violations, "stream", error)
        after_token_value: typing.Any = runtime_value.after_token
        if after_token_value is not None:
            if not (isinstance(after_token_value, str)):
                violations.append(
                    Violation(path="after_token", reason="expected string")
                )
            out["after_token"] = after_token_value
        max_records_value: typing.Any = runtime_value.max_records
        if max_records_value is not None:
            if not (
                not isinstance(max_records_value, bool)
                and (
                    isinstance(max_records_value, int)
                    or (
                        isinstance(max_records_value, float)
                        and max_records_value.is_integer()
                    )
                )
            ):
                violations.append(
                    Violation(path="max_records", reason="expected integer")
                )
            else:
                if abs(max_records_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="max_records", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if max_records_value < 1:
                    violations.append(
                        Violation(
                            path="max_records",
                            reason=f"must be >= 1, got {max_records_value}",
                        )
                    )
                if max_records_value > 1000:
                    violations.append(
                        Violation(
                            path="max_records",
                            reason=f"must be <= 1000, got {max_records_value}",
                        )
                    )
            out["max_records"] = max_records_value
        wait_ms_value: typing.Any = runtime_value.wait_ms
        if wait_ms_value is not None:
            if not (
                not isinstance(wait_ms_value, bool)
                and (
                    isinstance(wait_ms_value, int)
                    or (isinstance(wait_ms_value, float) and wait_ms_value.is_integer())
                )
            ):
                violations.append(Violation(path="wait_ms", reason="expected integer"))
            else:
                if abs(wait_ms_value) > 9007199254740991:
                    violations.append(
                        Violation(
                            path="wait_ms", reason="exceeds ±(2^53-1) integer cap"
                        )
                    )
                if wait_ms_value < 0:
                    violations.append(
                        Violation(
                            path="wait_ms", reason=f"must be >= 0, got {wait_ms_value}"
                        )
                    )
                if wait_ms_value > 60000:
                    violations.append(
                        Violation(
                            path="wait_ms",
                            reason=f"must be <= 60000, got {wait_ms_value}",
                        )
                    )
            out["wait_ms"] = wait_ms_value
        latest_only_value: typing.Any = runtime_value.latest_only
        if latest_only_value is not None:
            if not (isinstance(latest_only_value, bool)):
                violations.append(
                    Violation(path="latest_only", reason="expected boolean")
                )
            out["latest_only"] = latest_only_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadInput:
    """One read call: where to resume and how long to wait."""

    stream: StreamRef

    after_token: str | None = None
    """A cursor from an earlier record, read or append of this stream. The read resumes
    strictly after the record it names. Absent or empty starts at the oldest record the
    stream retains. A cursor from another stream or another store is refused, and one
    whose record retention dropped is refused as expired.
    """

    max_records: int | None = None
    """Answer with at most this many records. 100 when absent."""

    wait_ms: int | None = None
    """Wait at most this long for a record before answering. The handler shortens it to fit
    the request deadline. A call that collects nothing answers with no records and the
    caller's own cursor.
    """

    latest_only: bool | None = None
    """Answer with the cursor of the newest record and no records, for a reader that
    follows from now. Refused beside after_token.
    """


class _ReadOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadOutput"]
    ) -> "ReadOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        records_value: list[RecordWire] = typing.cast("typing.Any", None)
        if "records" not in raw or raw["records"] is None:
            violations.append(Violation(path="records", reason="required"))
        else:
            records_value_raw = raw["records"]
            if not isinstance(records_value_raw, list):
                violations.append(Violation(path="records", reason="expected array"))
            else:
                records_value_list: list[RecordWire] = []
                for records_value_index, records_value_element in enumerate(
                    typing.cast("list[typing.Any]", records_value_raw)
                ):
                    records_value_item_path = f"records[{records_value_index}]"
                    records_value_item_violation_count = len(violations)
                    records_value_item: RecordWire = typing.cast("typing.Any", None)
                    try:
                        records_value_item = (
                            _RecordWireTransferTypeConverter().from_transfer_type(
                                records_value_element, RecordWire
                            )
                        )
                    except temporalio.exceptions.ApplicationError as error:
                        _collect(violations, records_value_item_path, error)
                    if len(violations) == records_value_item_violation_count:
                        records_value_list.append(records_value_item)
                records_value = records_value_list

        next_token_value: str = typing.cast("typing.Any", None)
        if "next_token" not in raw or raw["next_token"] is None:
            violations.append(Violation(path="next_token", reason="required"))
        else:
            next_token_value_raw = raw["next_token"]
            if not isinstance(next_token_value_raw, str):
                violations.append(
                    Violation(path="next_token", reason="expected string")
                )
            else:
                next_token_value = next_token_value_raw

        done_value: bool = typing.cast("typing.Any", None)
        if "done" not in raw or raw["done"] is None:
            violations.append(Violation(path="done", reason="required"))
        else:
            done_value_raw = raw["done"]
            if not isinstance(done_value_raw, bool):
                violations.append(Violation(path="done", reason="expected boolean"))
            else:
                done_value = done_value_raw

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _READ_OUTPUT_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadOutput(
            records=records_value,
            next_token=next_token_value,
            done=done_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadOutput") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, ReadOutput):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        records_value: typing.Any = runtime_value.records
        if records_value is None:
            violations.append(Violation(path="records", reason="required"))
        else:
            records_violation_count = len(violations)
            if not (isinstance(records_value, list)):
                violations.append(Violation(path="records", reason="expected array"))
            if len(violations) == records_violation_count:
                records_checked = typing.cast("list[typing.Any]", records_value)
                records_out: list[typing.Any] = []
                for records_index, records_element in enumerate(records_checked):
                    try:
                        records_out.append(
                            _RecordWireTransferTypeConverter().to_transfer_type(
                                records_element
                            )
                        )
                    except temporalio.exceptions.ApplicationError as error:
                        _collect(violations, f"records[{records_index}]", error)
                out["records"] = records_out
        next_token_value: typing.Any = runtime_value.next_token
        if next_token_value is None:
            violations.append(Violation(path="next_token", reason="required"))
        else:
            if not (isinstance(next_token_value, str)):
                violations.append(
                    Violation(path="next_token", reason="expected string")
                )
            out["next_token"] = next_token_value
        done_value: typing.Any = runtime_value.done
        if done_value is None:
            violations.append(Violation(path="done", reason="required"))
        else:
            if not (isinstance(done_value, bool)):
                violations.append(Violation(path="done", reason="expected boolean"))
            out["done"] = done_value
        additional_properties_value: typing.Any = runtime_value.additional_properties
        if not isinstance(additional_properties_value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        checked_additional_properties = typing.cast(
            "dict[str, typing.Any]", additional_properties_value
        )
        for key, entry in checked_additional_properties.items():
            path = _member_path(key)
            if key in _READ_OUTPUT_DECLARED:
                violations.append(
                    Violation(
                        path=path,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadOutput:
    """What one read answered, and where to resume."""

    records: list[RecordWire]
    """The records after the caller's cursor, in stream order."""

    next_token: str
    """The cursor to pass as after_token next. The caller's own cursor when the call
    collected nothing.
    """

    done: bool
    """The stream ended for this reader: its owner's run chain is closed and every retained
    record after the cursor has been delivered. Nothing more will arrive, so the caller
    stops.
    """

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )


class _RecordWireTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["RecordWire", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["RecordWire"]
    ) -> "RecordWire":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        token_value: str = typing.cast("typing.Any", None)
        if "token" not in raw or raw["token"] is None:
            violations.append(Violation(path="token", reason="required"))
        else:
            token_value_raw = raw["token"]
            if not isinstance(token_value_raw, str):
                violations.append(Violation(path="token", reason="expected string"))
            else:
                token_value = token_value_raw

        record_value: bytes = typing.cast("typing.Any", None)
        if "record" not in raw or raw["record"] is None:
            violations.append(Violation(path="record", reason="required"))
        else:
            record_value_raw = raw["record"]
            if not isinstance(record_value_raw, str):
                violations.append(Violation(path="record", reason="expected string"))
            else:
                record_value_parsed = _parse_base64(
                    record_value_raw, "record", violations
                )
                if record_value_parsed is not None:
                    record_value = record_value_parsed

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _RECORD_WIRE_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return RecordWire(
            token=token_value,
            record=record_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "RecordWire") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, RecordWire):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        token_value: typing.Any = runtime_value.token
        if token_value is None:
            violations.append(Violation(path="token", reason="required"))
        else:
            if not (isinstance(token_value, str)):
                violations.append(Violation(path="token", reason="expected string"))
            out["token"] = token_value
        record_value: typing.Any = runtime_value.record
        if record_value is None:
            violations.append(Violation(path="record", reason="required"))
        else:
            record_violation_count = len(violations)
            if not (isinstance(record_value, bytes)):
                violations.append(Violation(path="record", reason="expected bytes"))
            if len(violations) == record_violation_count:
                out["record"] = _format_base64(record_value)
        additional_properties_value: typing.Any = runtime_value.additional_properties
        if not isinstance(additional_properties_value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        checked_additional_properties = typing.cast(
            "dict[str, typing.Any]", additional_properties_value
        )
        for key, entry in checked_additional_properties.items():
            path = _member_path(key)
            if key in _RECORD_WIRE_DECLARED:
                violations.append(
                    Violation(
                        path=path,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_RecordWireTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class RecordWire:
    """One record on the wire: its cursor and the record."""

    token: str
    """The cursor of this record. Pass it as after_token to resume past it."""

    record: bytes
    """The serialized temporal.sdk.streams.v1.StreamRecord: topic, kind, producer, attempt,
    sequence and body. The body is the producer's payload as its codec left it.
    """

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )


class _StreamRefTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["StreamRef", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["StreamRef"]
    ) -> "StreamRef":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        kind_value: str = typing.cast("typing.Any", None)
        if "kind" not in raw or raw["kind"] is None:
            violations.append(Violation(path="kind", reason="required"))
        else:
            kind_value_raw = raw["kind"]
            if not isinstance(kind_value_raw, str):
                violations.append(Violation(path="kind", reason="expected string"))
            else:
                kind_value = kind_value_raw

        workflow_id_value: str = typing.cast("typing.Any", None)
        if "workflow_id" not in raw or raw["workflow_id"] is None:
            violations.append(Violation(path="workflow_id", reason="required"))
        else:
            workflow_id_value_raw = raw["workflow_id"]
            if not isinstance(workflow_id_value_raw, str):
                violations.append(
                    Violation(path="workflow_id", reason="expected string")
                )
            else:
                workflow_id_value = workflow_id_value_raw

        run_id_value: str | None = None
        if "run_id" in raw:
            run_id_value_raw = raw["run_id"]
            if run_id_value_raw is None:
                run_id_value = None
            else:
                if not isinstance(run_id_value_raw, str):
                    violations.append(
                        Violation(path="run_id", reason="expected string")
                    )
                else:
                    run_id_value = run_id_value_raw

        topic_value: str = typing.cast("typing.Any", None)
        if "topic" not in raw or raw["topic"] is None:
            violations.append(Violation(path="topic", reason="required"))
        else:
            topic_value_raw = raw["topic"]
            if not isinstance(topic_value_raw, str):
                violations.append(Violation(path="topic", reason="expected string"))
            else:
                topic_value = topic_value_raw

        for key in raw:
            if (
                key != "kind"
                and key != "workflow_id"
                and key != "run_id"
                and key != "topic"
            ):
                violations.append(
                    Violation(path=_member_path(key), reason="unknown field")
                )
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return StreamRef(
            kind=kind_value,
            workflow_id=workflow_id_value,
            run_id=run_id_value,
            topic=topic_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "StreamRef") -> typing.Any:
        runtime_value: typing.Any = value
        if not isinstance(runtime_value, StreamRef):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        kind_value: typing.Any = runtime_value.kind
        if kind_value is None:
            violations.append(Violation(path="kind", reason="required"))
        else:
            if not (isinstance(kind_value, str)):
                violations.append(Violation(path="kind", reason="expected string"))
            out["kind"] = kind_value
        workflow_id_value: typing.Any = runtime_value.workflow_id
        if workflow_id_value is None:
            violations.append(Violation(path="workflow_id", reason="required"))
        else:
            if not (isinstance(workflow_id_value, str)):
                violations.append(
                    Violation(path="workflow_id", reason="expected string")
                )
            out["workflow_id"] = workflow_id_value
        run_id_value: typing.Any = runtime_value.run_id
        if run_id_value is not None:
            if not (isinstance(run_id_value, str)):
                violations.append(Violation(path="run_id", reason="expected string"))
            out["run_id"] = run_id_value
        topic_value: typing.Any = runtime_value.topic
        if topic_value is None:
            violations.append(Violation(path="topic", reason="required"))
        else:
            if not (isinstance(topic_value, str)):
                violations.append(Violation(path="topic", reason="expected string"))
            out["topic"] = topic_value
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


StreamRef: typing.TypeAlias = temporalio.contrib.streams.StreamRef
"""One stream, named by its owner and a topic. It names no cursor and no store, so the same
reference is good behind any endpoint that serves the owner.
"""
