# Generated by nexgen v0.2.8. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
)


@service(name="temporal.sdk.streams.v1.TemporalStreams")
class TemporalStreams:
    """Appends to and reads from streams through one Nexus endpoint, so the store behind it
    stays the endpoint's business and an operator can change it without touching
    callers. An append carries one batch and a read answers with a batch, because a
    Nexus operation per record costs too much for token streams. A record crosses as the
    serialized temporal.sdk.streams.v1.StreamRecord, the bytes every store keeps, so a
    caller in any language decodes it with that proto alone. The generated HTTP caller
    runs no payload codec, so it suits a namespace whose Workers use none. A Workflow
    caller goes through its Worker, whose codec applies.
    """

    append: Operation[
        AppendInput,
        AppendOutput,
    ] = Operation(name="append")
    """Write one batch as one producer attempt, or finish the producer. The store numbers
    the batch from sequence and deduplicates a retry: a repeat of the producer attempt's
    newest batch with the same content answers with where the original landed and writes
    nothing. A sequence already used with other content, or below the newest one the
    store holds for the attempt, is refused. Supersession records are never written: a
    reader synthesizes them from the attempts it observes.
    """

    read: Operation[
        ReadInput,
        ReadOutput,
    ] = Operation(name="read")
    """Answer with the records after the caller's cursor. The call waits until it has
    max_records records or wait_ms passes, whichever comes first, and answers with what
    it collected. It says when the stream has ended for the reader, so the caller can
    stop.
    """
