# Generated by nexgen v0.2.8. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service

from .models import (
    AttachStreamCallbackRequest,
    AttachStreamCallbackResponse,
    DetachStreamCallbackRequest,
    DetachStreamCallbackResponse,
    NotifyStreamRequest,
    NotifyStreamResponse,
    SignalWithStartWorkflowRequest,
    SignalWithStartWorkflowResponse,
)


@service(name="temporal.api.workflowservice.v1.WorkflowService")
class WorkflowService:
    """
    .. warning::
        This API is experimental and subject to change.
    """

    # .. warning:: This API is experimental and subject to change.
    signal_with_start_workflow: Operation[
        SignalWithStartWorkflowRequest,
        SignalWithStartWorkflowResponse,
    ] = Operation(name="SignalWithStartWorkflowExecution")

    attach_stream_callback: Operation[
        AttachStreamCallbackRequest,
        AttachStreamCallbackResponse,
    ] = Operation(name="AttachStreamCallback")

    detach_stream_callback: Operation[
        DetachStreamCallbackRequest,
        DetachStreamCallbackResponse,
    ] = Operation(name="DetachStreamCallback")

    notify_stream: Operation[
        NotifyStreamRequest,
        NotifyStreamResponse,
    ] = Operation(name="NotifyStream")
