# Generated by nexgen v0.2.4. DO NOT EDIT!

from __future__ import annotations

import dataclasses
import typing

import typing_extensions

import temporalio.converter
import temporalio.exceptions

from ._definitions import (
    Violation,
    _collect,
    _format_base64,
    _parse_base64,
    _parse_spec_integer,
    _transfer_type_convertible,
)

_APPEND_OUTPUT_DECLARED: frozenset[str] = frozenset({"cursor"})


_READ_OUTPUT_DECLARED: frozenset[str] = frozenset({"records", "next_token"})


_RECORD_WIRE_DECLARED: frozenset[str] = frozenset({"token", "frame"})


class _AppendInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendInput"]
    ) -> "AppendInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        workflow_id_value: str = typing.cast("typing.Any", None)
        if "workflow_id" not in raw or raw["workflow_id"] is None:
            violations.append(Violation(path="workflow_id", reason="required"))
        else:
            workflow_id_value_raw = raw["workflow_id"]
            if not isinstance(workflow_id_value_raw, str):
                violations.append(
                    Violation(path="workflow_id", reason="expected string")
                )
            else:
                workflow_id_value = workflow_id_value_raw

        stream_value: str = typing.cast("typing.Any", None)
        if "stream" not in raw or raw["stream"] is None:
            violations.append(Violation(path="stream", reason="required"))
        else:
            stream_value_raw = raw["stream"]
            if not isinstance(stream_value_raw, str):
                violations.append(Violation(path="stream", reason="expected string"))
            else:
                stream_value = stream_value_raw

        producer_id_value: str = typing.cast("typing.Any", None)
        if "producer_id" not in raw or raw["producer_id"] is None:
            violations.append(Violation(path="producer_id", reason="required"))
        else:
            producer_id_value_raw = raw["producer_id"]
            if not isinstance(producer_id_value_raw, str):
                violations.append(
                    Violation(path="producer_id", reason="expected string")
                )
            else:
                producer_id_value = producer_id_value_raw

        attempt_value: int = typing.cast("typing.Any", None)
        if "attempt" not in raw or raw["attempt"] is None:
            violations.append(Violation(path="attempt", reason="required"))
        else:
            attempt_value_raw = raw["attempt"]
            attempt_value_parsed = _parse_spec_integer(
                attempt_value_raw, "attempt", violations
            )
            if attempt_value_parsed is not None:
                attempt_value = attempt_value_parsed

        batch_index_value: int = typing.cast("typing.Any", None)
        if "batch_index" not in raw or raw["batch_index"] is None:
            violations.append(Violation(path="batch_index", reason="required"))
        else:
            batch_index_value_raw = raw["batch_index"]
            batch_index_value_parsed = _parse_spec_integer(
                batch_index_value_raw, "batch_index", violations
            )
            if batch_index_value_parsed is not None:
                batch_index_value = batch_index_value_parsed
                if batch_index_value < 1:
                    violations.append(
                        Violation(
                            path="batch_index",
                            reason=f"must be >= 1, got {batch_index_value}",
                        )
                    )

        topic_value: str | None = None
        if "topic" in raw:
            topic_value_raw = raw["topic"]
            if topic_value_raw is None:
                violations.append(
                    Violation(path="topic", reason="explicit null not allowed")
                )
            else:
                if not isinstance(topic_value_raw, str):
                    violations.append(Violation(path="topic", reason="expected string"))
                else:
                    topic_value = topic_value_raw

        payloads_value: list[bytes] | None = None
        if "payloads" in raw:
            payloads_value_raw = raw["payloads"]
            if payloads_value_raw is None:
                violations.append(
                    Violation(path="payloads", reason="explicit null not allowed")
                )
            else:
                if not isinstance(payloads_value_raw, list):
                    violations.append(
                        Violation(path="payloads", reason="expected array")
                    )
                else:
                    payloads_value_list: list[bytes] = []
                    for payloads_value_index, payloads_value_element in enumerate(
                        typing.cast("list[typing.Any]", payloads_value_raw)
                    ):
                        payloads_value_item_path = f"payloads[{payloads_value_index}]"
                        payloads_value_item_violation_count = len(violations)
                        payloads_value_item: bytes = typing.cast("typing.Any", None)
                        if not isinstance(payloads_value_element, str):
                            violations.append(
                                Violation(
                                    path=payloads_value_item_path,
                                    reason="expected string",
                                )
                            )
                        else:
                            payloads_value_item_parsed = _parse_base64(
                                payloads_value_element,
                                payloads_value_item_path,
                                violations,
                            )
                            if payloads_value_item_parsed is not None:
                                payloads_value_item = payloads_value_item_parsed
                        if len(violations) == payloads_value_item_violation_count:
                            payloads_value_list.append(payloads_value_item)
                    payloads_value = payloads_value_list

        finish_value: bool | None = None
        if "finish" in raw:
            finish_value_raw = raw["finish"]
            if finish_value_raw is None:
                violations.append(
                    Violation(path="finish", reason="explicit null not allowed")
                )
            else:
                if not isinstance(finish_value_raw, bool):
                    violations.append(
                        Violation(path="finish", reason="expected boolean")
                    )
                else:
                    finish_value = finish_value_raw

        for key in raw:
            if (
                key != "workflow_id"
                and key != "stream"
                and key != "producer_id"
                and key != "attempt"
                and key != "batch_index"
                and key != "topic"
                and key != "payloads"
                and key != "finish"
            ):
                violations.append(Violation(path=key, reason="unknown field"))
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendInput(
            workflow_id=workflow_id_value,
            stream=stream_value,
            producer_id=producer_id_value,
            attempt=attempt_value,
            batch_index=batch_index_value,
            topic=topic_value,
            payloads=payloads_value,
            finish=finish_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendInput") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        out["workflow_id"] = value.workflow_id
        out["stream"] = value.stream
        out["producer_id"] = value.producer_id
        if abs(value.attempt) > 9007199254740991:
            violations.append(
                Violation(path="attempt", reason="exceeds ±(2^53-1) integer cap")
            )
        out["attempt"] = value.attempt
        if abs(value.batch_index) > 9007199254740991:
            violations.append(
                Violation(path="batch_index", reason="exceeds ±(2^53-1) integer cap")
            )
        if value.batch_index < 1:
            violations.append(
                Violation(
                    path="batch_index", reason=f"must be >= 1, got {value.batch_index}"
                )
            )
        out["batch_index"] = value.batch_index
        if value.topic is not None:
            out["topic"] = value.topic
        if value.payloads is not None:
            out["payloads"] = [_format_base64(element) for element in value.payloads]
        if value.finish is not None:
            out["finish"] = value.finish
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendInput:
    """One append call: who is writing, where, and what."""

    workflow_id: str
    """The workflow whose stream is being written."""

    stream: str
    """The named stream to append to. Empty when the producer writes to a topic instead."""

    producer_id: str
    """Identifies the writer across its retries, so its attempts can be ordered."""

    attempt: int
    """The generation this producer is writing. A later attempt supersedes an earlier one."""

    batch_index: int
    """Counts this producer's batches from 1. The handler drops an index it has already
    written for this producer attempt, and rejects one that skips ahead or that resumes
    an attempt it never saw start.
    """

    topic: str | None = None
    """The topic to append to, when stream is empty."""

    payloads: list[bytes] | None = None
    """The records to write, each a serialized Temporal Payload. Empty on a call that only
    finishes.
    """

    finish: bool | None = None
    """Mark this producer done after writing the batch, so a reader stops waiting on it."""


class _AppendOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["AppendOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["AppendOutput"]
    ) -> "AppendOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        cursor_value: str | None = None
        if "cursor" in raw:
            cursor_value_raw = raw["cursor"]
            if cursor_value_raw is None:
                violations.append(
                    Violation(path="cursor", reason="explicit null not allowed")
                )
            else:
                if not isinstance(cursor_value_raw, str):
                    violations.append(
                        Violation(path="cursor", reason="expected string")
                    )
                else:
                    cursor_value = cursor_value_raw

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _APPEND_OUTPUT_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return AppendOutput(
            cursor=cursor_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "AppendOutput") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        if value.cursor is not None:
            out["cursor"] = value.cursor
        for key, entry in value.additional_properties.items():
            if key in _APPEND_OUTPUT_DECLARED:
                violations.append(
                    Violation(
                        path=key,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_AppendOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class AppendOutput:
    """Where the append landed, when the store can say."""

    cursor: str | None = None
    """Opaque token naming the last record written by this call. Absent when the call
    carried no payloads, when the batch was a repeat the handler dropped, or when the
    store learns positions only at read time.
    """

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )


class _ReadInputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadInput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadInput"]
    ) -> "ReadInput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        workflow_id_value: str = typing.cast("typing.Any", None)
        if "workflow_id" not in raw or raw["workflow_id"] is None:
            violations.append(Violation(path="workflow_id", reason="required"))
        else:
            workflow_id_value_raw = raw["workflow_id"]
            if not isinstance(workflow_id_value_raw, str):
                violations.append(
                    Violation(path="workflow_id", reason="expected string")
                )
            else:
                workflow_id_value = workflow_id_value_raw

        stream_value: str | None = None
        if "stream" in raw:
            stream_value_raw = raw["stream"]
            if stream_value_raw is None:
                violations.append(
                    Violation(path="stream", reason="explicit null not allowed")
                )
            else:
                if not isinstance(stream_value_raw, str):
                    violations.append(
                        Violation(path="stream", reason="expected string")
                    )
                else:
                    stream_value = stream_value_raw

        topic_value: str | None = None
        if "topic" in raw:
            topic_value_raw = raw["topic"]
            if topic_value_raw is None:
                violations.append(
                    Violation(path="topic", reason="explicit null not allowed")
                )
            else:
                if not isinstance(topic_value_raw, str):
                    violations.append(Violation(path="topic", reason="expected string"))
                else:
                    topic_value = topic_value_raw

        after_token_value: str | None = None
        if "after_token" in raw:
            after_token_value_raw = raw["after_token"]
            if after_token_value_raw is None:
                violations.append(
                    Violation(path="after_token", reason="explicit null not allowed")
                )
            else:
                if not isinstance(after_token_value_raw, str):
                    violations.append(
                        Violation(path="after_token", reason="expected string")
                    )
                else:
                    after_token_value = after_token_value_raw

        max_records_value: int | None = None
        if "max_records" in raw:
            max_records_value_raw = raw["max_records"]
            if max_records_value_raw is None:
                violations.append(
                    Violation(path="max_records", reason="explicit null not allowed")
                )
            else:
                max_records_value_parsed = _parse_spec_integer(
                    max_records_value_raw, "max_records", violations
                )
                if max_records_value_parsed is not None:
                    max_records_value = max_records_value_parsed
                    if max_records_value < 1:
                        violations.append(
                            Violation(
                                path="max_records",
                                reason=f"must be >= 1, got {max_records_value}",
                            )
                        )
                    if max_records_value > 1000:
                        violations.append(
                            Violation(
                                path="max_records",
                                reason=f"must be <= 1000, got {max_records_value}",
                            )
                        )

        wait_ms_value: int | None = None
        if "wait_ms" in raw:
            wait_ms_value_raw = raw["wait_ms"]
            if wait_ms_value_raw is None:
                violations.append(
                    Violation(path="wait_ms", reason="explicit null not allowed")
                )
            else:
                wait_ms_value_parsed = _parse_spec_integer(
                    wait_ms_value_raw, "wait_ms", violations
                )
                if wait_ms_value_parsed is not None:
                    wait_ms_value = wait_ms_value_parsed
                    if wait_ms_value < 0:
                        violations.append(
                            Violation(
                                path="wait_ms",
                                reason=f"must be >= 0, got {wait_ms_value}",
                            )
                        )
                    if wait_ms_value > 60000:
                        violations.append(
                            Violation(
                                path="wait_ms",
                                reason=f"must be <= 60000, got {wait_ms_value}",
                            )
                        )

        latest_only_value: bool | None = None
        if "latest_only" in raw:
            latest_only_value_raw = raw["latest_only"]
            if latest_only_value_raw is None:
                violations.append(
                    Violation(path="latest_only", reason="explicit null not allowed")
                )
            else:
                if not isinstance(latest_only_value_raw, bool):
                    violations.append(
                        Violation(path="latest_only", reason="expected boolean")
                    )
                else:
                    latest_only_value = latest_only_value_raw

        for key in raw:
            if (
                key != "workflow_id"
                and key != "stream"
                and key != "topic"
                and key != "after_token"
                and key != "max_records"
                and key != "wait_ms"
                and key != "latest_only"
            ):
                violations.append(Violation(path=key, reason="unknown field"))
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadInput(
            workflow_id=workflow_id_value,
            stream=stream_value,
            topic=topic_value,
            after_token=after_token_value,
            max_records=max_records_value,
            wait_ms=wait_ms_value,
            latest_only=latest_only_value,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadInput") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        out["workflow_id"] = value.workflow_id
        if value.stream is not None:
            out["stream"] = value.stream
        if value.topic is not None:
            out["topic"] = value.topic
        if value.after_token is not None:
            out["after_token"] = value.after_token
        if value.max_records is not None:
            if abs(value.max_records) > 9007199254740991:
                violations.append(
                    Violation(
                        path="max_records", reason="exceeds ±(2^53-1) integer cap"
                    )
                )
            if value.max_records < 1:
                violations.append(
                    Violation(
                        path="max_records",
                        reason=f"must be >= 1, got {value.max_records}",
                    )
                )
            if value.max_records > 1000:
                violations.append(
                    Violation(
                        path="max_records",
                        reason=f"must be <= 1000, got {value.max_records}",
                    )
                )
            out["max_records"] = value.max_records
        if value.wait_ms is not None:
            if abs(value.wait_ms) > 9007199254740991:
                violations.append(
                    Violation(path="wait_ms", reason="exceeds ±(2^53-1) integer cap")
                )
            if value.wait_ms < 0:
                violations.append(
                    Violation(
                        path="wait_ms", reason=f"must be >= 0, got {value.wait_ms}"
                    )
                )
            if value.wait_ms > 60000:
                violations.append(
                    Violation(
                        path="wait_ms", reason=f"must be <= 60000, got {value.wait_ms}"
                    )
                )
            out["wait_ms"] = value.wait_ms
        if value.latest_only is not None:
            out["latest_only"] = value.latest_only
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadInputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadInput:
    """One read call: where to resume from and how long to wait."""

    workflow_id: str
    """The workflow whose stream is being read."""

    stream: str | None = None
    """The named stream to read. Empty reads every stream the workflow publishes."""

    topic: str | None = None
    """Yield only records on this topic. Empty yields every topic. Only meaningful when
    stream is empty, because an inbound stream has no topics.
    """

    after_token: str | None = None
    """Opaque cursor from an earlier record or append. The read resumes strictly after the
    record it names, so a caller never sees that record twice. Empty starts at the
    beginning. The token is produced by whichever store sits behind the endpoint, so a
    caller cannot tell which one that is.
    """

    max_records: int | None = None
    """Return at most this many records. Defaults to 100 when omitted."""

    wait_ms: int | None = None
    """Wait at most this long for records to arrive before answering. The handler shortens
    it to fit the request deadline. A call that collects nothing answers with no records
    and the caller's own token.
    """

    latest_only: bool | None = None
    """Answer with the newest position and no records, for a reader that wants to follow
    from now.
    """


class _ReadOutputTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["ReadOutput", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["ReadOutput"]
    ) -> "ReadOutput":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        records_value: list[RecordWire] | None = None
        if "records" in raw:
            records_value_raw = raw["records"]
            if records_value_raw is None:
                violations.append(
                    Violation(path="records", reason="explicit null not allowed")
                )
            else:
                if not isinstance(records_value_raw, list):
                    violations.append(
                        Violation(path="records", reason="expected array")
                    )
                else:
                    records_value_list: list[RecordWire] = []
                    for records_value_index, records_value_element in enumerate(
                        typing.cast("list[typing.Any]", records_value_raw)
                    ):
                        records_value_item_path = f"records[{records_value_index}]"
                        records_value_item_violation_count = len(violations)
                        records_value_item: RecordWire = typing.cast("typing.Any", None)
                        try:
                            records_value_item = (
                                _RecordWireTransferTypeConverter().from_transfer_type(
                                    records_value_element, RecordWire
                                )
                            )
                        except temporalio.exceptions.ApplicationError as error:
                            _collect(violations, records_value_item_path, error)
                        if len(violations) == records_value_item_violation_count:
                            records_value_list.append(records_value_item)
                    records_value = records_value_list

        next_token_value: str | None = None
        if "next_token" in raw:
            next_token_value_raw = raw["next_token"]
            if next_token_value_raw is None:
                violations.append(
                    Violation(path="next_token", reason="explicit null not allowed")
                )
            else:
                if not isinstance(next_token_value_raw, str):
                    violations.append(
                        Violation(path="next_token", reason="expected string")
                    )
                else:
                    next_token_value = next_token_value_raw

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _READ_OUTPUT_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return ReadOutput(
            records=records_value,
            next_token=next_token_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "ReadOutput") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        if value.records is not None:
            records_out: list[typing.Any] = []
            for records_index, records_element in enumerate(value.records):
                try:
                    records_out.append(
                        _RecordWireTransferTypeConverter().to_transfer_type(
                            records_element
                        )
                    )
                except temporalio.exceptions.ApplicationError as error:
                    _collect(violations, f"records[{records_index}]", error)
            out["records"] = records_out
        if value.next_token is not None:
            out["next_token"] = value.next_token
        for key, entry in value.additional_properties.items():
            if key in _READ_OUTPUT_DECLARED:
                violations.append(
                    Violation(
                        path=key,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_ReadOutputTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class ReadOutput:
    """What one read call answered, and where to resume."""

    records: list[RecordWire] | None = None
    """The records after the caller's token, in stream order."""

    next_token: str | None = None
    """Opaque cursor to pass as after_token on the following call. Echoes the caller's own
    token when the call collected nothing.
    """

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )


class _RecordWireTransferTypeConverter(
    temporalio.converter.TransferTypeConverter["RecordWire", typing.Any]
):
    @typing_extensions.override
    def from_transfer_type(
        self, value: typing.Any, type_hint: type["RecordWire"]
    ) -> "RecordWire":
        violations: list[Violation] = []
        if not isinstance(value, dict):
            raise temporalio.converter.create_payload_validation_error(
                [Violation(path="", reason="expected object")]
            )
        raw = typing.cast("dict[str, typing.Any]", value)

        token_value: str = typing.cast("typing.Any", None)
        if "token" not in raw or raw["token"] is None:
            violations.append(Violation(path="token", reason="required"))
        else:
            token_value_raw = raw["token"]
            if not isinstance(token_value_raw, str):
                violations.append(Violation(path="token", reason="expected string"))
            else:
                token_value = token_value_raw

        frame_value: bytes = typing.cast("typing.Any", None)
        if "frame" not in raw or raw["frame"] is None:
            violations.append(Violation(path="frame", reason="required"))
        else:
            frame_value_raw = raw["frame"]
            if not isinstance(frame_value_raw, str):
                violations.append(Violation(path="frame", reason="expected string"))
            else:
                frame_value_parsed = _parse_base64(frame_value_raw, "frame", violations)
                if frame_value_parsed is not None:
                    frame_value = frame_value_parsed

        additional_properties: dict[str, typing.Any] = {}
        for key in raw:
            if key not in _RECORD_WIRE_DECLARED:
                additional_properties[key] = raw[key]
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return RecordWire(
            token=token_value,
            frame=frame_value,
            additional_properties=additional_properties,
        )

    @typing_extensions.override
    def to_transfer_type(self, value: "RecordWire") -> typing.Any:
        violations: list[Violation] = []
        out: dict[str, typing.Any] = {}
        out["token"] = value.token
        out["frame"] = _format_base64(value.frame)
        for key, entry in value.additional_properties.items():
            if key in _RECORD_WIRE_DECLARED:
                violations.append(
                    Violation(
                        path=key,
                        reason="additional property collides with declared property",
                    )
                )
            else:
                out[key] = entry
        if violations:
            raise temporalio.converter.create_payload_validation_error(violations)
        return out


@_transfer_type_convertible(_RecordWireTransferTypeConverter)
@dataclasses.dataclass(slots=True, kw_only=True)
class RecordWire:
    """One record on the wire: its cursor and its frame."""

    token: str
    """Opaque cursor naming this record. Pass it as after_token to resume just past it."""

    frame: bytes
    """The record frame, carrying the topic, kind, producer, attempt, sequence and body."""

    additional_properties: dict[str, typing.Any] = dataclasses.field(
        default_factory=dict
    )
