# Generated by nexgen v0.2.4. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
)


@service
class TemporalStreams:
    """The stream endpoint's two operations. One Temporal-authenticated endpoint hides the
    store behind it, so an operator switches storage without touching callers. Reads
    hand out batches and an append carries one batch per call, because a Nexus operation
    per record costs too much for token streams.
    """

    append: Operation[
        AppendInput,
        AppendOutput,
    ] = Operation(name="append")
    """Append one batch on the caller's account. The handler drops a batch_index it has
    already written for this producer attempt, so a retried call writes once, and
    rejects an index that skips ahead or a producer attempt it has no state for.
    Supersession records are not transported: a reader re-synthesizes them from the
    attempts it observes.
    """

    read: Operation[
        ReadInput,
        ReadOutput,
    ] = Operation(name="read")
    """Answer with the records after the caller's token, or time out. The call parks until
    it has max_records records or wait_ms elapses, whichever comes first, and returns
    whatever it collected.
    """
