# Generated by nexgen v0.2.4. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import Operation, service

from .models import (
    AppendInput,
    AppendOutput,
    ReadInput,
    ReadOutput,
)


@service
class TemporalStreams:
    """The stream endpoint's two operations. One Temporal-authenticated endpoint hides the
    store behind it, so an operator switches storage without touching callers. Reads
    hand out batches and an append carries one batch per call, because a Nexus operation
    per record costs too much for token streams. A record crosses as the serialized
    temporal.api.stream.v1.StreamRecord, the same bytes every store keeps, so a caller
    in any language decodes it with the api protos alone.
    """

    append: Operation[
        AppendInput,
        AppendOutput,
    ] = Operation(name="append")
    """Append one batch on the caller's account. The handler writes a batch once: a repeat
    of the last batch_index answers with where the original landed, and an index that
    skips ahead, one already behind the last, a sequence that does not continue, or a
    producer attempt the handler has no state for is refused. Supersession records are
    not transported: a reader re-synthesizes them from the attempts it observes.
    """

    read: Operation[
        ReadInput,
        ReadOutput,
    ] = Operation(name="read")
    """Answer with the records after the caller's token, or time out. The call parks until
    it has max_records records or wait_ms elapses, whichever comes first, and returns
    whatever it collected. It says when the store has ended the read, so the caller can
    stop.
    """
